### ISSUE TITLE
Swap Year and Language selectors?

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1015]
While looking at #986 , @sudheendrachari has suggested we swap the Year and Language selectors.

There are some advantages to this:
- Language is longer so can lead to concerns of going off screen, especially with the “Help Translate” option.
- More consistent with our URLs

On down side, it does remove the Year away from the other content links (ToC, Contributors and Methodology). I would expect Language Spector to be used the least.

If we do go for this change, I’d prefer to do it sooner rather than later before people get too used to where it is now.

Any thoughts? Will put voting buttons below so plus 1 them depending on your opinion.

**Comment by bazzadp** [comment]
Swap them around so Language and then Year

**Comment by bazzadp** [comment]
Leave them in the order they currently are (Year then Language).

**Comment by rviscomi** [comment]
No strong opinion. If there's an advantage to one way or the other, let's go with it! :)

**Comment by bazzadp** [comment]
Now I see this in #1026 I'm less convinced. I really think the year belongs with ToC/contributors/Methodology and Language should be on far right.

What do you think @rviscomi ?

@sudheendrachari how much of an issue do you think it will be to leave it as is?

**Comment by sudheendrachari** [comment]
We can surely try to leave it as is, and still try to style the dropdowns.
So to address #986 I tried few permutations of designs to see which fits best
 - Since language will be last item, we need to think about how we align drop down for it, considering they can be of variable width, in different languages. Couple of options here:
1. Align left edge of drop down to left edge of language button, and keep the dropdown width as fixed (The width can be pre-calculated since the distance of right edge of language button from viewport edge is known in advance, will be same for all languages more or less) This means text in it might wrap to next line if needed
<img width="782" alt="Screenshot 2020-07-14 at 10 38 46 PM" src="https://user-images.githubusercontent.com/10291571/87455273-cedd0380-c622-11ea-867d-1769e887fc91.png">

2. Align left edge of drop down to left edge of language button, but set the width such that it occupies maximum space till the right edge of the screen (barring few px, maybe) Since the dropdown will be positioned absolutely, i don't see a way to set variable width without using js (which will be only invoked once)
_Will look similar to approach 1 screenshot_

3. Align right edge of dropdown to right edge of language button, and let dropdown occupy width as needed while expanding to the left

**With text left aligned**

<img width="867" alt="Screenshot 2020-07-14 at 10 41 23 PM" src="https://user-images.githubusercontent.com/10291571/87455483-27140580-c623-11ea-8604-8b057e27b2fa.png">

**With text center aligned**

<img width="797" alt="Screenshot 2020-07-14 at 10 43 19 PM" src="https://user-images.githubusercontent.com/10291571/87455654-6b9fa100-c623-11ea-86d7-6349109c3f77.png">

For me approach (1) looks good, let me know your thoughts on these

**Comment by bazzadp** [comment]
1 works for me!

Lets close this issue and the PR and we can opened it, if 1 proves to be too difficult to implement.

**Comment by sudheendrachari** [comment]
Thanks.
(1) should be easy to implement, let's drop the PR i had raised also, i will raise with this style separately
