### ISSUE TITLE
Automatically track the translation status of each template/chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1047]
I'm drunk on the power of automation now! 😄 

Similar to #943, I'd love to be able to automatically track the translation status of templates/chapters across the various supported languages. @bazzadp is this also something you'd find useful?

We have https://github.com/HTTPArchive/almanac.httparchive.org/wiki/2019-Translation to track the status per chapter/language but we should also track the underlying templates. The emoji horserace is a fun way to visualize it, which we could also update automatically, but totally unnecessary.

I think the MVP for this would similarly be one data table of languages and templates/chapters for each year. Maybe each year's translation effort has its own separate tracking issue, but I can see the value in a single overview so new translators can jump in and see exactly where the gaps are. The most recent content should always be the highest priority though.

@bazzadp @ibnesayeed curious to hear what you think of this.

**Comment by ibnesayeed** [comment]
Any efforts on automation are worthy when there are enough dimensions to justify the upfront cost of automation and the kind of ongoing structure it needs. At this point I am not too familiar with the translation workflow and change frequency, so it is difficult for me to assess the need.

**Comment by bazzadp** [comment]
> I'm drunk on the power of automation now! 😄

Yes do love a bit of GitHub Actions!

Saying that I’m not convinced about this one. This changes very infrequently (unfortunately!) and each translate’s pull request is reviewed by a core maintainer -like any other PR and it’s only a little extra effort to update the workflow at that point.

If we automated it, ideally accepting a PR would update that languages tick at the top, and also [update the wiki status](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/2019-Translation) but really think that is too difficult.

I think the best, and easiest thing is to listen for edits on each translations status page and then count the number of tasks completed and update the wiki page. Still requires someone to tick that status page, but a lot of the Translations teams (but not all!) do that. Also my understanding is the wiki is effectively in a different repo, so this might be complicated to update?

We also use the [translation label](https://github.com/HTTPArchive/almanac.httparchive.org/labels/translation) for lots of things, unlike the 2020 Chapter page, so this may be prone to false positives. Unless we look for an issue with Translation label and the exact number of tasks. Or just hard code the list of translation issues. I’d probably go with that and would make it easier to differentiate year as well rather than trying to parse that or guess it.

All in all, until the Translation pace picks up a lot of steam (which it might do later in the year when we have lots of teams working on 2020 translations), I wouldn’t invest too much in this. However if automating the Wiki status update is relatively simple, then that is something I often forget to do so would be useful.
