### ISSUE TITLE
Should we add an RSS Feed?

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#1079]
I don’t use RSS myself but understand some do. Would provide a way of notifying subscribers when 2020 content goes online.

It would be very simple to set up the XML file to list articles, similar to the sitemap, though it would more complicated (and bigger!) to include full content [as some prefer](https://twitter.com/sarasoueidan/status/1061577409340809216?s=21).

Also what to do with translations? Include all languages on one feed with appropriate language attributes? Or separate feed for each language?

Any regular RSS users out there with any opinions?

**Comment by max-ostapenko** [comment]
RSS is definitely preferred  option when compared to newsletter.
And RSS per language is the way to go for sure.
But since the nature of Almanac is a yearly batch release there is no updates the rest of the year.
The content should be constantly be released for RSS to have some value.
Am I missing some regular content updates that currently happen?

**Comment by bazzadp** [comment]
Well informing people the 2020 edition is launched would be a good use of it. Most readers may see it launched on Twitter and the like but not all readers.

And for the translations they are released much more sporadically as each chapter is translated rather than in one big bang like English so do think there is value for those.

But, as I say, I personally never got into the whole RSS thing myself so not 100% sure. It was something I got asked by a few people got my own blog though and see some people asking for “more RSS feeds please” for blogs and the like so thought I’d throw the question out there.

**Comment by max-ostapenko** [comment]
Ok, let me do a step back. Is the goal here to extend the reach (increase audience) or improve communication channels with existing one?

There are three subscription channels I see now:
1 Twitter (3.6k users) - HTTP Archive updates and relevant tweets
2 GitHub (0.2k stars) - HTTP Almanac under the hood content
3 https://dev.to/httparchive/ - current HTTP Archive blog with RSS registered this year

@bazzadp As per your description I think the blog (item 3) with additional coverage of every year/language release will be a content that can be pushed via RSS.
I don't see the Almanac itself as a content for RSS feed: because of rare releases and book-like content batches.

Question is: does it make sense to move it from dev.to to https://httparchive.org/blog and create RSS here or add release coverage on dev.to?
@paulcalvano @rviscomi you've created a blog, you should have discussed this before I believe.

**Comment by bazzadp** [comment]
But again we don’t release languages in blocks with a full translation of all chapters.

Instead it’s like this:
- Nov - English 2019 released with all chapters. Actually we didn’t even do that, as we released a number (3 I think?) of “unedited” chapters initially as didn’t have tone to copy edit them, and then removed the unedited part later once we got round to that.
- Mar 2020 - released parts of French, Spanish and Japanese as part of #685 - note these were not full translations.
- Mar - now - released each chapter in those languages as they were completed.

At the moment only Japanese is fully translated, and even that isn’t in the ideal place as we only had one translator working to the end so chapters have not been peer reviewed. [Spanish only has a few chapters translated](https://github.com/HTTPArchive/almanac.httparchive.org/issues/498) (though looks like it will pick up pace again after some new blood has signed), and [French is about halfway through](https://github.com/HTTPArchive/almanac.httparchive.org/issues/539) and we’ve [a few other languages that have started, but not made any commits yet](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/2019-Translation).

So it is very much that a chapter or two will be released in a language every few weeks, rather than a language is launched fully translated in “book-like content batches” as you say. And those languages are often intermingled (I.e. we release a Spanish chapter, then a Japanese one, then a French one, then another Japanese one...etc.). We do often announce on Twitter when this happens but don’t think it’s worth a full blog post for that. When the whole Almanac is available in another language, or format (like ebook PDF) that makes more sense, but not for one of 20 chapters being available in one of 11 additional languages - or we’d potentially have 200 or so very bored blog posts!

We started thinking about holding of languages until we had the whole thing translated to that language, but soon realised we were sitting on content ready to go, and it was taking a lot longer (and some languages may never be complete as volunteers come and go) so went with the releasing of partial languages instead.

I’m also not thinking the releases option as you have raised in #1086 is really the right way either as doubt anyone wants to know about every tweak we make to the site, or every new chapter being launched in a language they don’t know. GitHub releases to me makes more sense when the software is consumed by other projects.

So one though was RSS feed and any Spanish speaker (for example) that uses RSS can subscribe and be notified when a new chapter is released.

Similarly any English RSS Subscriber, could have been notified when we launched the [2020 holding landing page](https://github.com/HTTPArchive/almanac.httparchive.org/pull/950) which included a call to action to get involved as the project kicked off.

However if RSS feed is wrong format for this then OK closing this issue. Was a thought and a question. However don’t think 2 and 3 are the right places for this either.

**Comment by rviscomi** [comment]
I'm not sure how useful RSS would be for annually updated content like ours. But if you think it'll help drive readership, let's do it.

**Comment by bazzadp** [comment]
Closing due to lack of interest. Can reopen again if people think we should do this.

**Comment by ouroboros8** [comment]
I use RSS more or less exclusively (unless you count twitter) to keep up with industry news, so this would be quite useful for me at least!

**Comment by tunetheweb** [comment]
@ouroboros8 I've just released this. Could you have a look at https://almanac.httparchive.org/en/rss.xml and see if it works in your RSS reader?
