### ISSUE TITLE
Add more spacing between featured chapter stats on mobile

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1434]
![image](https://user-images.githubusercontent.com/1120896/98420272-d3f01380-2054-11eb-9c21-05cf74415f3f.png)

I'm bad at design but it looks like these are too close together. Not sure what the right distance should be. Any help here appreciated.

**Comment by bazzadp** [comment]
I can't repeat this:

![Mobile view](https://user-images.githubusercontent.com/10931297/98469215-24db4580-21d6-11eb-9f3d-c8523a25d40c.png)

But think I did see it briefly when switching to mobile view in Chrome. See that occasionally where you need to switch a couple of times to pick up all the mobile styles.

Can you confirm this is a non-issue and close this if so? If not some more info would help.

**Comment by rviscomi** [comment]
Yeah I'm not able to reproduce the lack of space between the stats. However I still think there's a layout bug where there's not enough space between the stat and the label. I don't have a good eye to know what the right amount of spacing should be, but it does strike me as not having enough space.

Desktop:
![image](https://user-images.githubusercontent.com/1120896/99196078-0e923400-2758-11eb-9c0e-75b6c49aed51.png)

Mobile:
![image](https://user-images.githubusercontent.com/1120896/99196060-fa4e3700-2757-11eb-9640-9980ddcb9f09.png)

**Comment by bazzadp** [comment]
Yeah agree it could do with more spacing alright.

`h7` in the 2020 Markdown chapter was pointed out during editing and fix has just been released (markdown was used instead of HTML).

![Markdown featured chapter](https://user-images.githubusercontent.com/10931297/99199479-57b5a880-2797-11eb-8c1b-f11786d0b000.png)

What do you think about reducing the precision during next round of edits? 25.24KB seems a little precise and makes the number very big.

The rest of the issues you've raised are fixed in #1525

**Comment by rviscomi** [comment]
Agreed we could make the precision 1 or even 0 decimal places for this purpos.
