### ISSUE TITLE
Add instructions and on how to run super-linter locally

### ISSUE THREAD

**Issue by MSakamaki** [HTTPArchive/almanac.httparchive.org#1486]
https://github.com/HTTPArchive/almanac.httparchive.org/pull/1393#pullrequestreview-527958173

We can run a super-liner running in github actions locally.
I add the how to run to README.md.

https://github.com/github/super-linter/blob/master/docs/run-linter-locally.md

Optionally:
 - Do you have an idea to exclude unwanted folders such as node_modules from the target?

**Comment by bazzadp** [comment]
@MSakamaki I've been playing with this.

You're right it doesn't seem to exclude `node_modules` (and similar `env` for the python developers). You can filter exclude them but still takes a long while to run. Raised https://github.com/github/super-linter/issues/985

For now you could write a script and add it to package.json so we can call it with `npm run lint`. That would need to copy the following folders to `/tmp/lint`
- .github/linters
- src/templates/
- src/static/html/
- src/static/js/
- src/static/css/
- src/config
- server/
- main.py

and then run the following:

```
docker run -e RUN_LOCAL=true \                                                                                                                                                -e VALIDATE_ALL_CODEBASE=false \
         -e VALIDATE_BASH=true \
         -e VALIDATE_CSS=true \
         -e VALIDATE_HTML=true \
         -e VALIDATE_JAVASCRIPT_ES=true \
         -e VALIDATE_JSON=true \
         -e VALIDATE_MD=true \
         -e VALIDATE_PYTHON_PYLINT=true \
         -e VALIDATE_PYTHON_FLAKE8=true \
         -e VALIDATE_YAML=true \
         -v /tmp/lint:/tmp/lint github/super-linter
```

If that command fails the script should error with a message saying "Could not start super-linter. Are you sure you ran `docker pull github/super-linter:latest` to install it"? We don't want to run that every time as it's slow to install but think erroring out is good enough.

Next problem is that some of our generated templates fail to lint because of the `% set metadata = {...}` line. Surprised this hasn't bitten us before but we only lint HTML file after generating. 

Annoyingly [it doesn't look like HTMLLint has a way to ignore individual lines](https://github.com/htmlhint/HTMLHint/issues/161), but we can ignore the whole file (which is what happens when this runs through GitHub Actions) To do that we need to add this line:

```
<!--htmlhint attr-value-double-quotes:false -->
```

To the very top of the following files (before the `{% extends ... %}` line):
- src/templates/2019/chapter.ejs.html
- src/templates/2019/base_ebook.ejs.html

I think this would be a good addition to have for developers so very supportive of adding this. Let me know if you need any help with it!
