### ISSUE TITLE
Write content: Chapter 11. PWA

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#164]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
II. User Experience | 11. PWA | @tomayac @jeffposnick | @hyperpress | @jrharalson | #13 | #92

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/19BI3RQc_vR9bUPPZfVsF_4gpFWLNT6P0pLcAdL-A56c/edit?usp=sharing) and work with your analyst(s) (@jrharalson) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@hyperpress).
- [ ] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
👋 Greetings! Just checking in to make sure this is progressing and remind you of the October 7 deadline timed so we can launch at Chrome Dev Summit.

The checklist above indicates that you still need to review the results, write content, and get it reviewed. Feel free to reach out if you have any questions about the process.

**Comment by tomayac** [comment]
FYI, work on this chapter has started in [this document](https://docs.google.com/document/d/1MOt6doqXdL1yrvZvpRIDv37ulFpUBBj1cxLi_l8k1gQ/edit?usp=sharing).

**Comment by tomayac** [comment]
@hyperpress, if you have time, you can have a [first read](https://docs.google.com/document/d/1MOt6doqXdL1yrvZvpRIDv37ulFpUBBj1cxLi_l8k1gQ/edit#). Still in a *very* rough shape, but all stats are covered (pending Workbox).

**Comment by rviscomi** [comment]
@tomayac @jeffposnick the doc isn't publicly accessible. I'll start a PR so it's accessible for @hyperpress to review.

**Comment by bazzadp** [comment]
I all, I've just started reviewing this chapter as part of https://github.com/HTTPArchive/almanac.httparchive.org/issues/218 and have a few questions/comments. Thought I'd stick them here rather than as their own issue or as part of a PR for the copyedits for now. There will be a PR to come which you all can review and comment on.

@rviscomi there is currently a section on which BigQuery tables the data comes from. Personally I think it should be removed and covered in https://github.com/HTTPArchive/almanac.httparchive.org/issues/202. Also it doesn't mention the Almanac tables. Thoughts?

@tomayac , @jeffposnick and @hyperpress I'm a little confused with some of the stats in the ServiceWorker section:

- 0.44%/0.37% of pages crawled by HTTPArchive install a Service Worker (which is low as even popular pages are crawled only once - so that's fine).
- 15% of page loads are service worker controlled
- 1.56% of lighthouse pages are installable - how does that related to the two stats above? I thought a service worker was a pre-requisite to being installable and would have thought Lighthouse would have run on same set of pages as HTTPArchive as part of that crawl so confused as how it's so different from first stat. Also it's not a measure of all traffic either or it would be closer to second stat. So I'm confused. And think other readers might be too (or I'm just being an idiot). Happy to add a sentence explaining this as part of the copyedit review if you can explain it to me first 😀

I'm also suggesting writing a conclusion section for consistency as most other chapters have that. Want to write this? Or want me to have a stab at it and then you can review as part of the PR?

**Comment by rviscomi** [comment]
> @rviscomi there is currently a section on which BigQuery tables the data comes from. Personally I think it should be removed and covered in #202. Also it doesn't mention the Almanac tables. Thoughts?

Agreed. How we analyze the data is best left for the Methodology page, unless it's particularly relevant to the chapter.

> I'm also suggesting writing a conclusion section for consistency as most other chapters have that. Want to write this? Or want me to have a stab at it and then you can review as part of the PR?

To keep things moving go ahead and draft a conclusion and we can iterate on it. Thank you so much for working on this.

I'll leave the SW-specific questions to the others.

**Comment by bazzadp** [comment]
Any thoughts @tomayac , @jeffposnick and @hyperpress ?

**Comment by bazzadp** [comment]
Or @jrharalson who wrote these queries initially?

**Comment by bazzadp** [comment]
OK it would appear that these are separate requirements.

https://web.dev/installable-manifest/ states that you need basically four things to be installable:

1. Manifest
2. HTTPS
3. Service Worker
4. Some sort of engagement

I was presuming a Service Worker was part of the "Installable Manifest" criteria but it appears it's part of the larger "Installable" criteria. I don't think this is clear [so have raised an issue for this](https://github.com/GoogleChrome/web.dev/issues/1797).

Many sites have an installable manifest but no service worker. For example https://www.dropee.com/ gets the following in Lighthouse:

![image](https://user-images.githubusercontent.com/10931297/67940518-bd0a1c00-fbcb-11e9-92a8-cade50204122.png)

55,000 sites are in this category in HTTPArchive's July 2019 run meet this criteria (warning this query uses 1.22TB so don't run unless you have a good amount of credit!):

```
SELECT *
FROM `httparchive.lighthouse.2019_07_01_mobile`
WHERE JSON_EXTRACT_SCALAR(report, '$.audits.installable-manifest.score') = '1'
and JSON_EXTRACT_SCALAR(report, '$.audits.service-worker.score') = '0'

```
In fact only 20,000 sites meet both critera (uses a service worker and is installable) so just looking at installable manifests is over reporting by a large factor - which is exactly what we saw in this report and what confused me.

Will make some edits to the text to make this clear for any others like me who are easily confused.

**Comment by jeffposnick** [comment]
Hello @bazzadp! Thanks for your thorough reviews.

> In fact only 20,000 sites meet both critera (uses a service worker and is installable) so just looking at installable manifests is over reporting by a large factor - which is exactly what we saw in this report and what confused me. Will make some edits to the text to make this clear for any others like me who are easily confused.

Thanks, that sounds like a reasonable edit to make—reporting on how many sites actually meet all four of those conditions for installability sounds like a more meaningful stat than reporting on how many just meet the manifest criteria. (I wasn't fully aware of those distinctions in the way Lighthouse reported that data either.)

> I'm also suggesting writing a conclusion section for consistency as most other chapters have that. Want to write this? Or want me to have a stab at it and then you can review as part of the PR?

I'm not familiar with the style/tone used in the conclusion of the other chapters, so if you are and feel comfortable taking a stab at it, that would be great. Happy to review it after the fact.

**Comment by bazzadp** [comment]
Have done @jeffposnick as part of https://github.com/HTTPArchive/almanac.httparchive.org/pull/273. Comments appreciated but hoping to launch next week so if you could reviewer sooner rather than later then that would be appreciated!!

**Comment by rviscomi** [comment]
@tomayac @jeffposnick sorry for the delay, but this chapter finally has its data viz. Check it out here: https://almanac.httparchive.org/en/2019/pwa

Thanks again for your contributions! 👍 👍

**Comment by tomayac** [comment]
This looks beautiful, thank you very much for your hard work on this!
