### ISSUE TITLE
No OpenCart websites detected since April

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#165]
There are 0 OpenCart websites in the Ecommerce results for #135. This is definitely wrong.

![image](https://user-images.githubusercontent.com/1120896/65083118-ac804800-d975-11e9-91b5-65296520c796.png)

It turns out that this has been a bug since April. I found [this PR in Wappalyzer](https://github.com/AliasIO/Wappalyzer/pull/2668) made in April that changed the detection of OpenCart from an HTML regex to cookie-based. The presense of the `OCSESSID` cookie is the signal that's being detected.

Conveniently, we include the [demo.opencart.com](demo.opencart.com) website in our crawl, so this should be easy to reproduce. Here are the mobile test results from July: http://httparchive.webpagetest.org/result/190804_Mx59_ABWK/1/details/. Note that the `OCSESSID` cookie is being set in the first response:

![image](https://user-images.githubusercontent.com/1120896/65083357-53fd7a80-d976-11e9-9399-bd051b744fda.png)

However the list of technologies we detect on this page is missing OpenCart:

```sql
SELECT
  url,
  app
FROM
  `httparchive.technologies.2019_07_01_mobile`
WHERE
  url = 'https://demo.opencart.com/'
```

url | app
-- | --
https://demo.opencart.com/ | jQuery
https://demo.opencart.com/ | Bootstrap
https://demo.opencart.com/ | Font Awesome
https://demo.opencart.com/ | CloudFlare
https://demo.opencart.com/ | Google Font API
https://demo.opencart.com/ | PHP

@pmeenan is it possible that there's a problem with the WPT+Wappalyzer integration preventing cookie-based detections from matching? Could you look into this issue from the integration angle?

cc @samdutton @alankent

**Comment by rviscomi** [comment]
As a stopgap I can manually query for URLs containing that cookie and augment the `technologies.2019_07_01_*` tables.

**Comment by kyletaylored** [comment]
So following a bit on this. I was the creator of the PR that replaced the Regex detection for OpenCart detection. The original issue was that Wappalyzer was showing that [Google.com was built on OpenCart and PHP](https://github.com/AliasIO/Wappalyzer/issues/2650) (which we know isn't right). Looking at the regex, all it was doing was looking for a link that contained the text "opencart", which is why the results @rviscomi listed included sites like YouTube, Bing, and DuckDuckGo.

I couldn't find any other unique detection of OpenCart outside of this `OCSESSID` cookie being set on first request. The request does include `Set-Cookie` headers that would be more accurate to key off of, but this isn't possible to access those headers through JavaSCript and the Browser API for security reasons.

https://www.w3.org/TR/XMLHttpRequest/#the-getallresponseheaders%28%29-method

>Return all response headers, **excluding headers that are a case-insensitive match for Set-Cookie or Set-Cookie2**, as a single string, with each header line separated by a U+000D CR U+000A LF pair, excluding the status line, and with each header name and header value separated by a U+003A COLON U+0020 SPACE pair.

I think one thing we can agree on is that the data that was being collected up to this point is (probably) largely dirty data. I looked through OpenCart's API to see what JS objects are set (or scripts by name), and they're all incredibly vague and not accurate enough to detect. It's likely that you might need to remove detection for OpenCart from your service.

**Comment by rviscomi** [comment]
Thanks for following up @kyletaylored! IIUC you're saying that the cookie is the strongest signal for detecting OpenCart, but API limitations prevent us from actually measuring it? Does that mean detection for OpenCart is broken for everyone using Wappalyzer since the detections are all done in-browser? Now I wonder what other detections are cookie-based...

In our case, we integrate Wappalyzer with WebPageTest, which has lower level access to the network, so it should be feasible to sniff out the cookie. 🛎 @pmeenan to confirm how we're currently dealing with cookies in Wappalyzer detections.

**Comment by kyletaylored** [comment]
> Does that mean detection for OpenCart is broken for everyone using Wappalyzer since the detections are all done in-browser? Now I wonder what other detections are cookie-based...

If you're only checking on a first request where a cookie needs to be set and checked again, then it's probably broken. But also consider that most people using Wappalyzer are using it as a browser extension and they're revisiting sites, so those cookies are going to be set.
 
> In our case, we integrate Wappalyzer with WebPageTest, which has lower level access to the network, so it should be feasible to sniff out the cookie.

Yep, that would be your best bet if you're accessing them that way!
