### ISSUE TITLE
Localize numbers in figures

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1676]
For example, some figures have big numbers that include commas:

```html
{{ figure_markup(
  caption="The longest known alt text length.",
  content="15,357,625",
  classes="big-number",
  sheets_gid="TODO",
  sql_file="TODO.sql"
) }}
```

![image](https://user-images.githubusercontent.com/1120896/101532729-f4b4cd00-3962-11eb-96c4-d49a72feab09.png)

We can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString to show this number in the reader's locale or the locale corresponding to the selected translation, for example some locales use decimals as thousands separators: `15.357.625`.

**Comment by bazzadp** [comment]
Disagree!

This is in the markup and so can be changed during translated but don’t think we should otherwise localise these figures for English version when rest of the text (e.g. numbers in tables or text) will be in “English” format.

Plus I’m against just throwing Javascript at everything we can 😁

**Comment by rviscomi** [comment]
Of course! That makes  a lot more sense to just change the delimiter during the translation. 😅  (long day)
