### ISSUE TITLE
Figure overflow menu issue in Mobile view

### ISSUE THREAD

**Issue by sudheendrachari** [HTTPArchive/almanac.httparchive.org#1716]
Overflow menu for figures can get overlapped with figure itself. I believe we should be able to handle this in a better way

![A11Y - Overflow menu](https://user-images.githubusercontent.com/10291571/101673923-d099de80-3a7d-11eb-8531-8ec3c0aec7ec.png)

**Comment by bazzadp** [comment]
Yes this was realised in https://github.com/HTTPArchive/almanac.httparchive.org/pull/1570#issuecomment-738568155 but we ran out of time to resolve and figured it happened rarely nough and the value of exposing the data more easily was worth dealing with this short term.

Would love to hear thoughts on how you think we should resolve? Or if you can resolve it would gladly take a PR!

For what it's worth I still think it should be in the figure caption rather than top right as don't think that make sense for tables, but @rviscomi disagrees 😀 Or maybe it should be in both places for charts but figure caption only for large images and tables? Best of both worlds?

What do you think?
