### ISSUE TITLE
Fetch well-known URLs

### ISSUE THREAD

**Issue by nrllh** [HTTPArchive/almanac.httparchive.org#2211]
I think we should discuss including well-known URLs (e.g., `robots.txt`, `ads.txt`, `security.txt`, etc.) because I see two problems there;

1. Even if one of these URLs is being fetched by our crawler, not all people know about that (I was noticed that last year `security.txt` was used by the SEO chapter, and we actually could also use it for our security chapter, we did not because we (or I 😊) didn't know it.)

2. Fetching these URLs may cost more time, but I think it's in general essential to analyze these URLs and enrich our analysis. We can fetch these files once in a year for the Almanac.
 
My suggestion is to collect interesting URLs in this issue so all contributors know which URLs are being fetched additionally.

I found a list but it doesn't include all URLs: https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers - for example, `manifest.json`, `hackers.txt` are missing in that list.

So what do you think?

**Comment by nrllh** [comment]
For the security chapter `security.txt`, `hackers.txt` and `robots.txt` would be interesting.

|  name  | path   |  
|---|---|
| robots.xt  |  /robots.txt | 
|  security.txt | .well-known/security.txt|  
|  hackers.txt | /hackers.txt  |  

cc @SaptakS @tomvangoethem

**Comment by rockeynebhwani** [comment]
@nrllh  - Last year, I tried to do this for eCommerce chapter by looking at following well-known URLs

.well-known/assetlinks.json
.well-known/apple-app-site-association

My commit from last year is in custom_metrics/ecommerce.js (https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/ecommerce.js) 

I was trying to find out how many eCommerce sites have Android/iOS app and using these standards to declare the app association. I didn't end up including any insights in eCommerce chapter as I ran out of time and for some platforms, I was getting empty assetlinks.json file so in order to get to something meaningful for the chapter, I needed to further parse the content of the file and just detecting the presence of file was not enough. 

Tagging eCommerce 2021 team if the team want to pick up this - @bobbyshaw @rrajiv

**Comment by rviscomi** [comment]
One issue with WPT is that fetching additional URLs in the custom metric does not necessarily make their requests/responses available in the network log that makes up the `requests` and `response_bodies` tables. So we would either have to dump the response bodies in the output of the custom metric or only output some summary statistics about the file. The latter is preferable because we don't know how long some of these files will be and we don't want to bloat the HAR file (made available in the `pages` tables). @nrllh could you clarify which approach you're proposing?

cc @pmeenan in case there's a way to make custom metric requests visible in the requests/bodies.

**Comment by bazzadp** [comment]
I actually quite like the fact it doesn’t appear in requests/bodies. Means you’re not polluting the relay page load. Otherwise number of requests goes up by one for each requested additional load, and number of 404s could sky rocket as most sites won’t have a lot of these files.

Do agree we should ideally do the processing in the custom metric though and only save summary results back, rather than full file.

**Comment by nrllh** [comment]
There is a lot to explore in these files. In robots.txt, it'll be interesting to analyze (for security chapter) potential exploitation (e.g., secret login links). In security.txt we can check which popular reporting methods are being used. 

That's why I think providing the response body of these files would be better than providing some statistics. Otherwise, it could also be a limitation for future analysis. Of course, if it doesn't cause an overhead.

**Comment by GJFR** [comment]
To be completely sure: currently the consensus is for analysts to use custom metrics to collect information on the content of .well-known URLs, right? Or is this information going to be included in the crawl dataset, such that it will be available by query?

Just want to avoid redundant data/work :)

**Comment by GJFR** [comment]
I've extended and renamed `ecommerce.js` to `well_known.js` in https://github.com/HTTPArchive/legacy.httparchive.org/pull/219/commits/2a441a09ad49f8fcb9ddbf98cf6ebb7116d2c584.

It should be easily extendible for other well-known URLs and external sources by just adding `parseResponse` calls while passing the desired URL, and -- if required -- a parser function.
