### ISSUE TITLE
Investigate quality of July 2021 Lighthouse results

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2289]
Lighthouse tests in the July crawl may have been affected by https://github.com/GoogleChrome/lighthouse/issues/12835. We should analyze the July table to see how many LH reports are unusable. If it's really bad we may need to use the June dataset for Web Almanac research, or wait for the August crawl if LH v8 is important.

**Comment by tunetheweb** [comment]
I've actually run some tests for PWA chapter on the results and didn't notice anything odd.

Looking at the dashboard the size of the data, and the number of rows has gone down ever so slightly:

![Lighthouse table sizes](https://user-images.githubusercontent.com/10931297/128024498-64f2462e-45a4-4c83-adee-6dfa3fc50471.png)

The size may be explained by [no longer tracking LCP images](https://twitter.com/patmeenan/status/1402718181496705029?s=20) but number of rows should have gone up not down based on [number of pages tested](https://httparchive.org/reports/state-of-the-web#numUrls) (7,452,047 in June -> 7,499,763 in July)

Running this query:

```sql
SELECT json_extract_scalar(report, '$.userAgent') as chromeVersion, json_extract_scalar(report, '$.lighthouseVersion') as lighthouseVersion, count(1)
FROM `httparchive.lighthouse.2021_07_01_*`
GROUP BY chromeVersion, lighthouseVersion
ORDER BY count(1) desc
```

We get this:

chromeVersion | lighthouseVersion | number of tests
-- | -- | --
Chrome/91.0.4472.114 | 8.0.0 | 4,197,952
Chrome/91.0.4472.164 | 8.1.0 | 1,728,047
Chrome/92.0.4515.107 | 8.1.0 | 758,425
Chrome/91.0.4472.114 | 8.1.0 | 576,120
Chrome/91.0.4472.114 | 7.0.1 | 1,063
Chrome/91.0.4472.164 | 7.0.1 | 305
Chrome/92.0.4515.107 | 7.0.1 | 305

(note I've extracted the relevant bit of the user-agent).

We have 7,262,217 tests that came back with a JSON result of some sort (out of an expected 7,499,763 - so 97% of expected results) and some of them were for Chrome 82/Lighthouse 8.1.1 (which I understand is the bad combination - @pmeenan / @patrickhulce can you confirm?).

I'm presuming if it failed we'd get no JSON out at all? Is that a fair assumption?

It also could be the crash caused it to be retried (not sure if it does - @pmeenan ?) in which case it might have been successful second or third time. Which might explain why the numbers are small.

So to me it looks like we can use July data for the Almanac, even if a few failed due to this bug.

WDYT?

**Comment by pmeenan** [comment]
We'd get no json but it was a 100% failure so retries wouldn't have helped.  Looks like most of the crawl completed before 92 rolled out so we should be good (mobile may have been impacted a bit more since it runs longer).

**Comment by tunetheweb** [comment]
> mobile may have been impacted a bit more since it runs longer

But we don't run Lighthouse on desktop and only the combo of Chrome and Lighthouse that affects it so only mobile is impacted anyway?

**Comment by pmeenan** [comment]
Doh, sorry. You're right. Ignore me.
