### ISSUE TITLE
Line height of links causes inconsistent paragraph spacing

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2435]
> ![image](https://user-images.githubusercontent.com/1120896/140418827-557cbd91-f142-4fcd-ba40-d3914d4a49eb.png)

In the screenshot above, the text is all in one paragraph but the spacing around the lines is different depending on whether it contains a link. There might be a bug in the link's line-height style causing the inconsistency.

The spacing around "possible." almost makes it look like a separate paragraph.

**Comment by MukulKolpe** [comment]
Hey @rviscomi can I work on this issue?

**Comment by rviscomi** [comment]
@MukulKolpe go for it!

**Comment by tunetheweb** [comment]
Any luck wiht this @MukulKolpe ?

I looks to me like it's due to the `vertical-align: super;` on line 1577:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/f4d55ae7431ed68e09b4c87b959921d2e439c7d2/src/static/css/almanac.css#L1559-L1570

This is done for our translations to indicate when a link is not in the translated language but in English:

![Screenshot of French chapter with (en) text above English links](https://user-images.githubusercontent.com/10931297/140584539-4e4f13c0-99d3-4229-9a1f-7dece20b5642.png)

In English we actually turn this off:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/f4d55ae7431ed68e09b4c87b959921d2e439c7d2/src/static/css/almanac.css#L1581-L1587

If we change that turning off from `content: ''` to `content: initial` is seems to fix it for English but then translations are still bad.

It seems this is a tough one to solve from a quick Google: https://stackoverflow.com/questions/1530685/html-sup-tag-affecting-line-height-how-to-make-it-consistent

Alternatively we could just show the `(en)` on hover and focus? That's probably less distracting for our foreign readers  anyway rather than loads of random `(en)`'s dotted about the page? downside would be the line hint jumping on hover/tabbing. @borisschapira you originally proposed this feature if I recall correctly. Do you have an opinion here?

**Comment by MukulKolpe** [comment]
I'm stuck with some work for a few days. So I might not be able to work on this right now...It will be better if someone else takes this up for now. Sorry for taking so much time.

**Comment by tunetheweb** [comment]
With a bit more Googling I found the answer: https://css-tricks.com/snippets/css/prevent-superscripts-and-subscripts-from-affecting-line-height/ Should have known CSS Tricks would have something!

Will still set it to `initial` in English to remove the pointless empty pseudo element.

**Comment by tunetheweb** [comment]
Oh and turns out we have this fix in our normalize.css file too! Should have looked there and applied same thing here :-(

https://github.com/HTTPArchive/almanac.httparchive.org/blob/48ed8ad71792f477f0a3d2c793c17843978e99a5/src/static/css/normalize.css#L120-L135
