### ISSUE TITLE
CMS 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2896]
# CMS 2022

![CMS illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/cms/hero_lg.jpg)

If you're interested in contributing to the CMS chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @sirjonathan | @sirjonathan | @alexdenning @dknauss @alonkochba @honzasladek | @csliva | @dknauss | @tunetheweb  |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 CMS resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-cms on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/1vaA7fumol1iWDvjYvUnVRpykOABLppJmhYNUnD7DDvY/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/cms
[~google-sheets]: https://docs.google.com/spreadsheets/d/1HvTcCEw9LeMNX-fI_yOy0HemKFYKaQAHBxtB0etakqY/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/cms.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by tunetheweb** [comment]
Calling the 2021 CMS super team!: @alonkochba @alankent @andreylipattsev @logicalphase @saterchris @rviscomi @TosinArasi 

Are any of you interested in contributing again this year?

Also can any of you suggest potential authors/reviewers/analysts who have domain expertise in the CMS space that might make good contributors? Would love if you could reach out and/or tag suggestions here to see if we can get new people involved!

**Comment by csliva** [comment]
I'm an analyst under the SEO section, but we have plenty of help over there. I can help with CMS as an analyst here as well. 

I've used and built sites for wordpress, joomla, hubspot, drupal, shopify, ghost, contentful, magento, django, and Adobe experience manager so I should have the domain experience here.

**Comment by tunetheweb** [comment]
Excellent, would love to have you on board @csliva !

**Comment by honzasladek** [comment]
Hi @tunetheweb I'm happy to help with this. 

I can help with some content about headless CMS space. (Note: I'm currently doing https://github.com/contember which is a headless CMS so would need good reviewers to not introduce some bias into this chapter.)

Otherwise I've got 16 years of experience building websites. Including CMSes like Wordpress, Drupal, Joomla, Strapi, Directus, Sylius (not so much a cms), Prismic, Netlify CMS, ....

**Comment by tunetheweb** [comment]
Thanks @honzasladek , presume you're looking to author / co-author the chapter then?

**Comment by sirjonathan** [comment]
@tunetheweb I'm happy to serve as lead author. I spoke with @alexdenning and he's happy to be a reviewer. @honzasladek, if you're up for it, I'd love to work with you as a reviewer - your experience in a wide range of CMS and the fact that you're focused now on Contember would bring some great perspective into the mix.

**Comment by alonkochba** [comment]
Great to see the CMS chapter having an author. I can also assist in reviewing and anything you want to know about last year's chapter or data.

**Comment by honzasladek** [comment]
@sirjonathan Sounds great, happy to participate as a reviewer!

**Comment by tunetheweb** [comment]
Thank you for agreeing to be the lead @sirjonathan !!

One of the first thing's I'll hand over to you @sirjonathan is maintenance of the first comment at the top of this issue. If you could ensure that's kept up to date with contributors that join and leave, be aware of the milestones and dates, and tick off each of these as you complete them. We have an [overall Web Almanac issue tracker](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2908), that's automatically driven based on the info in that comment. And since we now have a full team, you can no tick off Milestone 0!

And @sirjonathan @alexdenning @alonkochba @honzasladek and @csliva if you could all request access to [the CMS doc](https://docs.google.com/document/d/1vaA7fumol1iWDvjYvUnVRpykOABLppJmhYNUnD7DDvY/edit) and start brainstorming ideas of what you want to include in the chapter.

We also have the HTTP Archive CMS slack channel if you could all join that?

It would be good to review previous years chapters and data to get a sense of what we're looking to create here:

Year | Chapter | Results Sheet
----- | ---- | ----
2021 | [2021 CMS Chapter](https://almanac.httparchive.org/en/2021/cms) | [2021 Results Sheet](https://docs.google.com/spreadsheets/d/1gAJh4VcSEU6-6aQxBiTFl-7cbyHukfdhg-Iaq9y5pnc/)
2020 | [2020 CMS Chapter](https://almanac.httparchive.org/en/2020/cms) | [2020 Results Sheet](https://docs.google.com/spreadsheets/d/1vTf459CcCbBuYeGvgo-RSidppR62SfM-VTkW-dfS3K4/)
2019 | [2019 CMS Chapter](https://almanac.httparchive.org/en/2019/cms) | [2019 Results Sheet](https://docs.google.com/spreadsheets/d/1FDYe6QdoY3UtXodE2estTdwMsTG-hHNrOe9wEYLlwAw/)

Some tips and advice from me, if I may be so bold:
- Review all of [last year's CMS queries](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/cms) and data and decide which you will likely want to use again this year. @csliva can then work on updating them to 2022.
- Use them to consider new ideas for this year to differentiate the chapter, rather than it being just the exact same as previous years with refreshed data.
- We are planning on using the 1st June data for the 2022 Web Almanac so that gives us exactly 1 month to get any new custom metrics in there so don't have huge amount of time. Custom metrics are bits of JavaScript we run on the rendered DOM to gather more information than the raw HTTP response bodies gives it - which is MUCH more accurate, easier (and cheaper!) to query than running regexs over raw HTML responses that don't even include any JavaScript created elements. Look at [our current list of raw metrics](https://github.com/HTTPArchive/custom-metrics/tree/main/dist) that we use in our run to get some idea.
- We also use Wappalyzer to detect technologies - including CMS. Here's the list of CMSes it detects: https://www.wappalyzer.com/technologies/cms. Are there any major ones missing? Can they be detected (note [some CMSes  cannot be detected by it](https://twitter.com/eleven_ty/status/1287174616113393664?s=20&t=azD8z0GOKvJqSl467SVFNg)?). If so, can we open an issue (or better yet a PR!) to Wappalyzer before 1st June to detect that so we'll have it for our analysis?

Many chapters find it helpful to have a kick off call with the team - to put faces to names, and introduce yourselves. I'\m happy to join that if you want to set it up @sirjonathan ?

I'll be keeping a close eye on the chapter and feel free to reach out to me here/Slack/Twitter/Email if you have any questions or thoughts.

**Comment by amandeepsinghvirdi** [comment]
If I am not too late, I am happy to contribute as Author or Analyst.  My experience and bio can be found here: https://byaman.com/about/

**Comment by tunetheweb** [comment]
@amandeepsinghvirdi has since agreed to take on Ecommerce lead so not sure if the offer is still there as might be busy with that one.

**Comment by tunetheweb** [comment]
@sirjonathan @alexdenning @alonkochba @honzasladek @csliva we still don't have a draft outline so have missed our 15th May deadline. This means the chances of adding any NEW data to the 1st June crawl is getting slimmer by the day (since we don't yet know what we want to capture) so you may have to just rely on the existing data that HTTP Archive already collects.

But , it's still not too late. So I would suggest:
1. Copying last years outline into the doc as a basic first step and then iterating on that.
2. Reviewing the [results from last year](https://docs.google.com/spreadsheets/d/1gAJh4VcSEU6-6aQxBiTFl-7cbyHukfdhg-Iaq9y5pnc/), and the [queries from last year](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/cms/) to see if that encourages any thoughts on new data you might want that wasn't considered last year.
3. Review the [CMS technologies captured by Wappalyzer](https://www.wappalyzer.com/technologies/cms) to see if anything major is missing that we might want to see if we can get added

Happy to answer any questions on any of this!

**Comment by sirjonathan** [comment]
@tunetheweb Thank you for the reminders and the support! I've been gathering notes / ideas over the past week and reviewing the previous years results. I will make sure the outline is drafted and ready for review this week. 

Also, @dknauss who serves as Editor over at Post Status, is up for being a reviewer.

**Comment by tunetheweb** [comment]
Sent you an invite to the GitHub org @dknauss so you can edit issues and the like.

**Comment by sirjonathan** [comment]
@tunetheweb I've [updated the draft doc with an outline](https://docs.google.com/document/d/1vaA7fumol1iWDvjYvUnVRpykOABLppJmhYNUnD7DDvY/edit), using last year as a starting point. 

I've added a few questions as comments within the doc that I'd love feedback on.

No changes in queries from last year stand out to me. One thing I am curious about is if we can include s[ome comparisons to Shopify](https://github.com/wappalyzer/wappalyzer/issues/6256#issuecomment-1133451774) or, perhaps more efficiently, we could do some collaboration with [the Ecommerce chapter team](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2897).

**Comment by tunetheweb** [comment]
Hey all, apologies I've been a bit quiet lately, but been travelling and not had too much Almanac time lately.

How are we looking now? Milestone 2's date has passed by quite a bit now, but the crawl is still going on (not sure if you saw [Rick's update on Slack in the Web Almanac channel](https://httparchive.slack.com/archives/CGFLV2S06/p1654718157281299)?), so that gives us a bit of time to catch up.

We didn't need to add any new Custom Metrics for this chapter, so we just need to open a draft PR with a list of queries to write to complete that Milestone (note you do not need to have the queries written to complete Milestone 2 - just have a list of them). You can see [example open PRs for the other chapters already open](https://github.com/HTTPArchive/almanac.httparchive.org/pulls).

As it looks like you're just currently planning to reuse last year's queries that should be an easy task! @csilva as the analyst for this chapter can one of you do this? You can also copy all the queries from `sql/2021/cms` to `sql/2022/cms` directory and update the dates from `202110701` to `202206021` to really get ahead of the game and be ready to run them when the crawl finishes.

> No changes in queries from last year stand out to me. One thing I am curious about is if we can include shttps://github.com/wappalyzer/wappalyzer/issues/6256#issuecomment-1133451774 or, perhaps more efficiently, we could do some collaboration with https://github.com/HTTPArchive/almanac.httparchive.org/issues/2897.

That definitely should be possible. Should just be a matter of replacing:

```sql
WHERE  category = 'CMS'
```

with:

```sql
WHERE  category = 'CMS' or App = 'Shopify'
```

Just need to decide if you want to run all queries with this, or only some of them? Or perhaps you want to run some or all queries twice (once with this, once without) to allow comparison to pervious years for some metrics?

**Comment by csliva** [comment]
Thanks for the directions @tunetheweb. I'll go ahead and get that PR drafted. I will also see what we can do about platforms like Shopify. Shopify includes a blog and it is very much in the game for Content Management.

**Comment by tunetheweb** [comment]
Hey @sirjonathan and @csliva, just to let you know that the data is all ready to start querying, so you can start writing (and even running) your queries. Ones that are straight copies of last year you can probably just run (with the updated dates of course), but if you do come up with any new ones, then might wanna ping the other analysts (including myself!) to have a quick review before running the full query (unless it's a very small, quick table in which case go right ahead).

Do reach out if you've any questions or need any help. Looking forward to seeing what insights you find!

**Comment by sirjonathan** [comment]
Hey y'all. The [draft is ready for review](https://docs.google.com/document/d/1vaA7fumol1iWDvjYvUnVRpykOABLppJmhYNUnD7DDvY/edit#) and per discussion with @csliva, we're slated to have all feedback incorporated and the text complete by Friday, September 9, in order to allow sufficient time for markdown generation for the 15th deadline.

Overall, I've [kept the structure from last year](https://almanac.httparchive.org/en/2021/cms), simplifying in a few places and adding additional data where we have it (in particular, the Page Builders section).

Of the current draft, two items remain from my perspective:

1. WordPress in 2022 - I'd like to incorporate any relevant highlights from 2021 on performance improvements in core development. @dknauss are there any items that come to mind for you, beyond the work of the Core Performance team?

2. Conclusion - I've left the current conclusion in draft mostly unchanged from @alonkochba's work last year. After incorporating any further feedback, I'll take a fresh pass at it.

@alexdenning @alonkochba @dknauss @honzasladek Would you [review the draft](https://docs.google.com/document/d/1vaA7fumol1iWDvjYvUnVRpykOABLppJmhYNUnD7DDvY/edit#) over the next few days and add in any comments or suggestions you have? I'll monitor your feedback throughout the week and then submit my final pass on Friday.

Thank y'all for your help!
