### ISSUE TITLE
Ecommerce 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2897]
# Ecommerce 2022

![Ecommerce illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/ecommerce/hero_lg.jpg)

If you're interested in contributing to the Ecommerce chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @amandeepsinghvirdi | @amandeepsinghvirdi @himani-kankaria | @alankent @bobbyshaw @rockeynebhwani | @jrharalson | @shantsis | @tunetheweb |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 Ecommerce resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-ecommerce on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/1IsdOo8Tgjo4aLDdYZaTGc42BNnJIZMziqPBgNzqCYYg/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/ecommerce
[~google-sheets]: https://docs.google.com/spreadsheets/d/1UXCD_A748UF79McCg1cdLdCKPKE8JNFAdd1l-t-glrI/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/ecommerce.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by alankent** [comment]
Happy to help as a reviewer again if useful!

**Comment by shantsis** [comment]
Happy to join as an editor

**Comment by tunetheweb** [comment]
Calling the 2021 Ecommerce super team!: @bobbyshaw @rockeynebhwani @alankent @soulcorrosion @fili @rrajiv

Are any of you interested in contributing again this year? I see some of you have already commented above so that's great!

Also can any of you suggest potential authors/reviewers/analysts who have domain expertise in the Ecommerce space that might make good contributors? Would love if you could reach out and/or tag suggestions here to see if we can get new people involved!

**Comment by himani-kankaria** [comment]
I'm new to this and the process of building a chapter, but I would be happy to contribute as an author. 

And even I would like to recommend Vatsal Shah - https://in.linkedin.com/in/vatsalshah. *Don't know if he is here on Github.

**Comment by tunetheweb** [comment]
@himani-kankaria could you give a little info about yourself and your expertise in this area as your GitHub bio is a little bare.

**Comment by amandeepsinghvirdi** [comment]
Would love to contribute as Author or Analyst.  My experience/bio can be found here: https://byaman.com/about/

**Comment by tunetheweb** [comment]
Thank you for agreeing to be the lead @amandeepsinghvirdi !!

One of the first thing's I'll hand over to you @amandeepsinghvirdi is maintenance of the first comment at the top of this issue. If you could ensure that's kept up to date with contributors that join and leave, be aware of the milestones and dates, and tick off each of these as you complete them. We have an [overall Web Almanac issue tracker](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2908), that's automatically driven based on the info in that comment. And since we now have a full team, you can no tick off Milestone 0!

And @amandeepsinghvirdi @himani-kankaria @alankent@bobbyshaw @shantsis if you could all request access to [the Ecommerce doc](https://docs.google.com/document/d/1IsdOo8Tgjo4aLDdYZaTGc42BNnJIZMziqPBgNzqCYYg/edit) and start brainstorming ideas of what you want to include in the chapter.

We don’t currently have an analysts for this chapter , but if you know anyone with SQL skills and Ecommerce domain knowledge that might be interested in please do reach out. In meantime I can help out on that side.

We also have the [HTTP Archive Ecommerce slack channel](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) if you could all join that?

It would be good to review previous years chapters and data to get a sense of what we're looking to create here:

Year | Chapter | Results Sheet
----- | ---- | ----
2021 | [2021 Ecommerce Chapter](https://almanac.httparchive.org/en/2021/ecommerce) | [2021 Results Sheet](https://docs.google.com/spreadsheets/d/1HCfrXJ52lV46UvxOvDVjJj70fOeFVrTTD8DUm0tPVXE/)
2020 | [2020 Ecommerce Chapter](https://almanac.httparchive.org/en/2020/ecommerce) | [2020 Results Sheet](https://docs.google.com/spreadsheets/d/1Hvsh_ZBKg2vWhouJ8vIzLmp0nLIMzrT2mr6RQbIkxqY/)
2019 | [2019 Ecommerce Chapter](https://almanac.httparchive.org/en/2019/ecommerce) | [2019 Results Sheet](https://docs.google.com/spreadsheets/d/1FUMHeOPYBgtVeMU5_pl2r33krZFzutt9vkOpphOSOss/)

Some tips and advice from me, if I may be so bold:
- Review all of [last year's Ecommerce queries](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/ecommerce) and data and decide which you will likely want to use again this year. We can then work on updating them to 2022.
- Use them to consider new ideas for this year to differentiate the chapter, rather than it being just the exact same as previous years with refreshed data.
- We are planning on using the 1st June data for the 2022 Web Almanac so that gives us exactly 1 month to get any new custom metrics in there so don't have huge amount of time. Custom metrics are bits of JavaScript we run on the rendered DOM to gather more information than the raw HTTP response bodies gives it - which is MUCH more accurate, easier (and cheaper!) to query than running regexs over raw HTML responses that don't even include any JavaScript created elements. Look at [our current list of raw metrics](https://github.com/HTTPArchive/custom-metrics/tree/main/dist) that we use in our run to get some idea.
- We also use Wappalyzer to detect technologies - including Ecommerce sites. Here's the list of Ecommerce technologies it detects: https://www.wappalyzer.com/technologies/cms. Are there any major ones missing? Can they be detected. If so, can we open an issue (or better yet a PR!) to Wappalyzer before 1st June to detect that so we'll have it for our analysis?

Many chapters find it helpful to have a kick off call with the team - to put faces to names, and introduce yourselves. I'm happy to join that if you want to set it up @amandeepsinghvirdi ?

I'll be keeping a close eye on the chapter and feel free to reach out to me here/Slack/Twitter/Email if you have any questions or thoughts.

**Comment by amandeepsinghvirdi** [comment]
Thank you for the detailed instructions @tunetheweb!  Very helpful! 

I'll work with contributors to check their availability and schedule a call accordingly.

**Comment by himani-kankaria** [comment]
Hello everyone, out of curiosity, would I be required to do coding? Because
I'm from a marketing background in the eCommerce domain. Please suggest how
this entire process happens. Thanks.

Regards,
Himani Kankaria
Website <https://missivedigital.com/> | LinkedIn
<https://www.linkedin.com/in/himanikankaria/> | Twitter
***@***.***_kankaria>
*Helping businesses become brands.*

**Comment by tunetheweb** [comment]
Hi @himani-kankaria

For the Author and Reviewer role no coding would be required - though being able to dig through data ([example of last years results](https://docs.google.com/spreadsheets/d/1HCfrXJ52lV46UvxOvDVjJj70fOeFVrTTD8DUm0tPVXE/)) would definitely be needed for the Author role.

The Analyst role would require SQL and JS coding.

There's a breif description of each role [in the first comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2897#issue-1202155190), under the **Expand for more information about each role 👀** text. There's also [more in depth details in our wiki](https://github.com/HTTPArchive/almanac.httparchive.org/wiki).

If interested to get involved then adding some suggestions in [the doc outline](https://docs.google.com/document/d/1IsdOo8Tgjo4aLDdYZaTGc42BNnJIZMziqPBgNzqCYYg/edit) as to what this chapter should look at would be a great start (request edit access to be able to edit this). We should consider what to repeat from previous years (links above), what new stuff to add to differentiate this from previous years, what's changed in last year in ecommerce space (or due to change in the near future)...etc.

Depending on how you get on, you can decide (along with @amandeepsinghvirdi as the lead of the chapter) as to whether you end up co-authoring and actually writing some of the chapter, or just suggesting and reviewing

**Comment by tunetheweb** [comment]
@amandeepsinghvirdi @amandeepsinghvirdi @himani-kankaria @alankent @bobbyshaw  @shantsis reminder to access the [planning doc](https://docs.google.com/document/d/1IsdOo8Tgjo4aLDdYZaTGc42BNnJIZMziqPBgNzqCYYg/edit?usp=sharing) and start adding your ideas to the outline. What's new with Ecommerce this year, or what topics would be interesting to revisit from previous years?

We're hoping to have the outline **completed by May 15** to give us enough time to add any needed custom metrics to the June crawl before it kicks off. Thanks!

Would it also be helpful to have a video chat to introduce yourselves to each other? Here's a suggested agenda some of the other chapters are using for that: https://docs.google.com/document/d/1nqPjvY0zg2YJda3ghIJuvVaSeY_wbz_nwBK15tHULsg/edit?usp=sharing

I'm happy to attend anything you all set up. I'm UK timezone, but reasonably flexible.

**Comment by tunetheweb** [comment]
@rrajiv any interest in analysing this chapter again this year?

**Comment by rrajiv** [comment]
Hi @tunetheweb  - interest is always there but time isn't. ;) I have signed up to review the caching chapter this time so won't have time to be an analyst again for ecommerce. If things change I will let you know

**Comment by jrharalson** [comment]
@tunetheweb I can help out with Analysis this yr if needed. Just let me know

**Comment by tunetheweb** [comment]
Excellent @jrharalson - was resigned to having to step in here if we couldn’t get anyone 😁

**Comment by amandeepsinghvirdi** [comment]
@jrharalson @bobbyshaw @himani-kankaria @shantsis @alankent @tunetheweb 
- Is everyone available for a quick 30 min call this week or weekend? I believe we have contributors from across the world with different time zones. So schedule can be bit hard. Can you please add your availability here? I can send Google/Zoom invite based on common availability.

I have pretty flexible schedule on Friday and over the weekend. So any time will work for me.


**Meeting Agenda:**
https://docs.google.com/document/d/1nqPjvY0zg2YJda3ghIJuvVaSeY_wbz_nwBK15tHULsg/edit?usp=sharing

**Ecommerce - 2022 Document**
https://docs.google.com/document/d/1IsdOo8Tgjo4aLDdYZaTGc42BNnJIZMziqPBgNzqCYYg/edit
**Action Item:** Please request edit access and add your info in this document. 

Most of you have contributed to Web Almanac in the past. So any suggestions, guidance will be greatly appreciated.

**Comment by tunetheweb** [comment]
I'm pretty flexible too from Friday afternoon (I'm in Ireland - so UK time), or any time over weekend.

**Comment by rockeynebhwani** [comment]
I am ok Friday or Weekend anytime. I am in London.

**Comment by himani-kankaria** [comment]
I am okay with Friday. I'm in India.


Regards,
Himani Kankaria
Website <https://missivedigital.com/> | LinkedIn
<https://www.linkedin.com/in/himanikankaria/> | Twitter
***@***.***_kankaria>
*Helping businesses become brands.*

**Comment by tunetheweb** [comment]
@amandeepsinghvirdi @jrharalson @bobbyshaw @himani-kankaria @shantsis @alankent we still don't have a draft outline so have missed our 15th May deadline. This means the chances of adding any NEW data to the 1st June crawl is getting slimmer by the day (since we don't yet know what we want to capture) so you may have to just rely on the existing data that HTTP Archive already collects.

But , it's still not too late. So I would suggest:
1. Copying last years outline into the doc as a basic first step and then iterating on that.
2. Reviewing the [results from last year](https://docs.google.com/spreadsheets/d/1HCfrXJ52lV46UvxOvDVjJj70fOeFVrTTD8DUm0tPVXE/edit), and the [queries from last year](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/ecommerce/) to see if that encourages any thoughts on new data you might want that wasn't considered last year.
3. Review the [Ecommerce technologies captured by Wappalyzer](https://www.wappalyzer.com/technologies/ecommerce) to see if anything major is missing that we might want to see if we can get added

Happy to answer any questions on any of this!

**Comment by amandeepsinghvirdi** [comment]
Hello Team,

Apologies for the delay here. I'll wrap this up today and share the outline document here for your feedback.

**Comment by amandeepsinghvirdi** [comment]
I have updated the Ecommerce (Web Almanac 2022) 
https://docs.google.com/document/d/1IsdOo8Tgjo4aLDdYZaTGc42BNnJIZMziqPBgNzqCYYg/edit#

I will need to update the Tools section. I have added some comments for some particular topics to confirm if we can retrieve that data/metrics.

**Comment by tunetheweb** [comment]
@amandeepsinghvirdi I had a quick look through the outline there and see @rviscomi beat me to the punch and has already responded to your queries.

I'm not seeing anything so far that would suggest we need to add anything to the crawl so think we're in a good state from that perspective.

I also think we're good to tick off milestone 1 at the top of this issue (well let you do that as we're trying to encourage the chapter leads to own this meta data).

@jrharalson do you want to start thinking about how to gather this information? Obviously can use last years's ecommerce queries as a starting point.

**Comment by jrharalson** [comment]
I took a peak at last year's queries which look pretty good. @tunetheweb I'll likely have some questions to refresh my memory in a few syntax spots. I do plan to poke around in the Wappalyzer again next week - as it is always so wild to see the key Enterprise tier HCL/SFCC/SAP-Hybris platforms track at such low counts.

**Comment by amandeepsinghvirdi** [comment]
@jrharalson - Are you available over this weekend for 30 minutes to review the queries/metrics?

**Comment by tunetheweb** [comment]
Hey @amandeepsinghvirdi @himani-kankaria @rockeynebhwani @jrharalson, just to let you know that the data is all ready to start querying, so you can start writing (and even running) your queries. Ones that are straight copies of last year you can probably just run (with the updated dates of course), but if you do come up with any new ones, then might wanna ping the other analysts (including myself!) to have a quick review before running the full query (unless it's a very small, quick table in which case go right ahead).

Do reach out if you've any questions or need any help. Looking forward to seeing what insights you find!

**Comment by tunetheweb** [comment]
@amandeepsinghvirdi @himani-kankaria I've just merged the queries and looks like the data is in the [spreadheet](https://docs.google.com/spreadsheets/d/1UXCD_A748UF79McCg1cdLdCKPKE8JNFAdd1l-t-glrI/edit#gid=1551910747).

We now have a little over two weeks to get the chapter **written, reviewed, and edited** by the end of the month.

@jrharalson I see a number of tabs marked as "Not in Git" - is that still the case? If so should these tabs be removed? Or should the queries be added to git? Bit confused to be honest.

We're almost done now!

**Comment by tunetheweb** [comment]
@amandeepsinghvirdi @himani-kankaria I've not heard from you in quite a while, and not seeing any progress on the doc. Just checking that you're still interested and intending to write this chapter?

**Comment by amandeepsinghvirdi** [comment]
@tunetheweb - I am planning to write this over this weekend and then we can start the review process end of next week.

**Comment by tunetheweb** [comment]
Great to hear @amandeepsinghvirdi 

I've gone though the data and added a few charts. Still some more to do here so will come back to it later.

**Comment by tunetheweb** [comment]
Finished all the charts now. Let me know if any questions.

**Comment by amandeepsinghvirdi** [comment]
Thank you @tunetheweb ! I'll ping on slack if I come across any issues/questions.

**Comment by rviscomi** [comment]
@amandeepsinghvirdi given that the draft is mostly incomplete and we're a few weeks past the deadline to have the chapter fully written, reviewed, and edited, it's not looking like we'll be able to publish this chapter and we'll have to close it. I'm really sorry to everyone who put a lot of effort into it already, but for a highly distributed project like this, it's important for all chapters to adhere to the core timeline.

That said, I know you've been working in a separate doc, so if there's more to the chapter than what I'm seeing in the [official doc](https://docs.google.com/document/d/1IsdOo8Tgjo4aLDdYZaTGc42BNnJIZMziqPBgNzqCYYg/edit?usp=sharing), please update it and coordinate with your reviewers/editors to get it wrapped up ASAP. It's too late to be included in Monday's launch but if you're committed and have the time, I think we could try to release it in a couple of weeks as other delayed chapters are completed. Let me know if that's what you'd like to do.

Either way, no hard feelings, I know things come up and we're in uncertain/unpredictable times. Wish you the best.
