### ISSUE TITLE
Investigate 0 web mentions

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#3236]
https://almanac.httparchive.org/en/2022/css#reactions

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1120896/196787945-5094faaa-114c-428a-b182-fe26b4d133aa.png">

Why does a popular chapter like CSS appear to have 0 likes and 0 reposts? The data suggests that this isn't very well-liked or popular, which isn't the case. Is there any way to improve the accuracy of these stats? If not, is it worth showing them?

**Comment by tunetheweb** [comment]
Web Mentions come from:
- Blogs that have implemented ping backs
- A less reliable scrape of our @HttpArchive Twitter account, because Twitter does not integrate WebMentions natively.

Most are from the latter. And especially "likes".

[Looking at that](https://twitter.com/search?q=%40httparchive%20https%3A%2F%2Falmanac.httparchive.org%2Fen%2F2022%2Fcss&src=typed_query&f=live) we only have 4 likes. So yeah it missed some (not uncommon) but not like posts WE have posted have huge numbers of likes.

It would be great if it could pick up on other people's Tweets but at the moment it can't. When [I last spoke to the WebMention people](https://github.com/snarfed/bridgy/issues/1092#issuecomment-986090288), they were waiting on a new Twitter API to make it a bit more reliable, but even then not sure if it will pick up Tweets from others.

**Comment by tunetheweb** [comment]
Or TLDR - Post more from @HTTPArchvie account rather than just retweet others 😉

**Comment by tunetheweb** [comment]
Hmmm.... there's no Likes nor Reposts for any of our chapters as far as I can see.

I wonder if there's more afoot here. Maybe they changed the API.

Digging...

**Comment by tunetheweb** [comment]
https://github.com/snarfed/bridgy/issues/1329

**Comment by tunetheweb** [comment]
So this was partially fixed (there was an issue in Bridgy with Twitter accounts with capital letters - like HTTPArchive has).

It still doesn't pick up WebMentions with a fragment/hash url (e.g. https://almanac.httparchive.org/en/2022/css#reactions) but that's a limitation of WebMentions at the mo: https://github.com/aaronpk/webmention.io/issues/106

Closing this as investigation is complete and we've got what we can get for now.
