### ISSUE TITLE
Standardize on "third party" or "third-party"

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#339]
We're inconsistent throughout the chapters on the usage of a hyphen in "third-party". It's even used both ways in the Third Parties chapter.

I've read https://www.merriam-webster.com/dictionary/third-party and I'm still confused about how to use it. Any grammaticians who can weigh in?

@HTTPArchive/editors

**Comment by paulcalvano** [comment]
Looking at the dictionary entry, I guess it comes down to whether we're using the term as a noun or an adjective. 

I personally prefer "third party" without the hyphen. But I also believe it is frequently used as an adjective - so "third-party content" would be grammatically correct for most uses in the almanac.

**Comment by bazzadp** [comment]
Agreed. That's what I went with when I copy edited the Third Party chapter. It's a third party with talking about a particular party (noun), but third-party content (adjective of the content) and third-party resource (adjective of the resource).

I'm still torn about the chapter title itself - is it Third Parties because we are talking about the parties themselves? Or is that short for "third-party content on websites"? I left it with the former...

**Comment by LPardue** [comment]
Agree with Bazza, it might appear as inconsistent but both forms are completely consistent with grammar rules.

**Comment by rviscomi** [comment]
TIL!
