### ISSUE TITLE
What about having a bio for every contributor ? 

### ISSUE THREAD

**Issue by AymenLoukil** [HTTPArchive/almanac.httparchive.org#350]
What about having a bio for every contributor ?

**Comment by rviscomi** [comment]
IMO it only makes sense for authors because their credentials add authority to their chapters. In the Contributors page designs we had a line for everyone to have their own tagline; just a few words about themselves like "SEO expert" or "World-class accessibility speaker". We can look into bringing that back if there's interest.

**Comment by bazzadp** [comment]
I'm going to close this. I think now we've launched and we're getting less interaction from the wider team this would be a huge effort to implement on most of the contributors and, like @rviscomi , I'm not convinced of the need. Maybe one for the 2020 edition.

Feel free to reopen if you strongly disagree.
