### ISSUE TITLE
Media 2024

### ISSUE THREAD

**Issue by nrllh** [HTTPArchive/almanac.httparchive.org#3596]
# Media 2024

![Media illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/media/hero_lg.jpg)

If you're interested in contributing to the Media chapter of the 2024 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). You might be interested in exploring the changes to this year's version [here](https://github.com/HTTPArchive/almanac.httparchive.org/discussions/3619).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- |    -------  |
| @stefanjudis | @stefanjudis | @svgeesus, @nhoizey, @eeeps   | @foolip, @nucliweb, @eeeps, @scottjehl| @MichaelLewittes  | @turban1988  | 

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [0. Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
- [x] 📆 `April 15` Complete program and content committee - 🔑 *Organizing committee*
  - The content team has at least one author, reviewer, and analyst.

### [1. Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
- [x] 📆 `May 1` **First meeting to outline the chapter contents** - 🔑 *Content team*
  - The content team has completed the chapter outline.

### [2. Gather data](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
- [x] 📆 `June 1` **Custom metrics completed** - 🔑 *Analysts*
  - Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress. 
- [x]  📆 `June 1` **HTTP Archive Crawl** - 🔑 *HA Team*
  - HTTP Archive runs the June crawl.

### [3. Validate results](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
- [x] 📆 `August 15` **Query Metrics & Save Results** - 🔑 *Analysts*
  - Analysts have queried all metrics and saved the output.

### [4. Draft content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
- [x] 📆 `September 15` **First Draft of Chapter** - 🔑 *Authors*
  - Authors has written the chapter. 
- [x] 📆 `October 10` **Review & Edit Chapter** - 🔑 *Reviewers & Editors*
  - Reviewers and  Editors has processed the the chapter.

### [5. Publication](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
- [x] 📆 `October 15` **Chapter Publication (Markdown & PR)** - 🔑 *Authors*
  - Authors has converted the chapter to markdown and drafted a PR.
- [ ] 📆 `November 1` **Launch of 2024 Web Almanac 🚀** - 🔑 *Organizing committee*
 
### [6. Virtual conference](#)
- [ ] 📆 `November 20` **Virtual Conference** - 🔑 *Content Team*

<a id="chapter-resources"></a>
## [Chapter resources](#chapter-resources)
Refer to these 2024 Media resources throughout the content creation process:
[📄 Google Docs](https://docs.google.com/document/d/1aIMU2N03Fof01066KuMseVdlVdlEmwUGRsB5LsJIOZE/edit) for outlining and drafting content
[🔍 SQL files](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2024/media/README.md) for committing the queries used during analysis
[📊 Google Sheets](https://docs.google.com/spreadsheets/d/1Q2ITOe6ZMIXGKHtIxqK9XmUA1eQBX9CLQkxarQOJFCk/edit#gid=1778117656) for saving the results of queries
[📝 Markdown file](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2024/media.md) for publishing content and managing public metadata
[💻 Collab notebook](https://colab.research.google.com/drive/15Sapz-hUU3FdRyD9BjUIWI9repiReNyM) for collaborative coding in Python - if needed
[💬 #web-almanac-media](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) on Slack for team coordination

**Comment by MichaelLewittes** [comment]
I'd be happy to be the editor of the media section again. Know the drill -- and able ready to do it once more.

**Comment by foolip** [comment]
I'm interested in contributing as an analyst.

I've been poking around at the question "what sizes and qualities do images on the web tend to be?" I've been running some of the queries in https://almanac.httparchive.org/en/2022/media again and have identified what I think are a few interesting angles.

First, the distribution of images sizes is much more uneven and interesting than https://almanac.httparchive.org/en/2022/media#image-dimensions suggests. Here's a histogram from a quick experiment I did in February:

![image](https://github.com/HTTPArchive/almanac.httparchive.org/assets/498917/198ea1e1-5b35-446e-9eed-ad2c95023041)

Instead of megapixels I'm using sqrt(megapixels), so the equivalent width of a square image. I found this much easier to reason about, since much of the interesting action is in the 0-0.25 megapixel range. 300x300 images are the most common.

Second, BPP (bits/pixel) strongly depends on image size, with smaller images having higher BPP. The reasons I can see are (1) container overhead (2) more incentive to compress large images and (3) less detail in large images, as many small images are downscaled versions of the large ones.

I think it would be interesting to try to understand quality both through BPP while taking these effects into account, but also by estimating the encoder settings used. I suspect the latter varies less with size, and at least from JPEG an estimation is possible due to how the format works. A first attempt yielded this:

![image](https://github.com/HTTPArchive/almanac.httparchive.org/assets/498917/c204f264-b376-475e-a8b2-54ae671379ea)

I also shared this in https://github.com/HTTPArchive/almanac.httparchive.org/issues/3572#issuecomment-1943549499 and there are some words of caution about using ImageMagick's detected quality, but I think something useful could be done here.

**Comment by foolip** [comment]
A colleague made this useful observation:

> noting that 300x300 is the default (medium) image size in WordPress and 82 is the default quality. This lines up exactly with the "most common" size and quality.  Since WordPress sites are a large part of the dataset (~30%) they may be influencing the results. It might be interesting to see what images on non WordPress sites looks like.

**Comment by svgeesus** [comment]
I volunteer ~~as tribute~~ as a reviewer

**Comment by nucliweb** [comment]
Hi, I am also happy to contribute as an analyst.

**Comment by nrllh** [comment]
Hey @eeeps @akshay-ranganath @nhoizey @yoavweiss  @MichaelLewittes - awesome contributors from previous years 🙂 Are you interested in joining us again this year?

**Comment by MichaelLewittes** [comment]
Would be honored to join again as the editor.

**Comment by nhoizey** [comment]
Hi @nrllh, I can indeed join this year once again, as a reviewer.

**Comment by nrllh** [comment]
thank yuo @MichaelLewittes, @nhoizey, @eeeps!

**Comment by turban1988** [comment]
Hi @rey-dal,
Thank you very much for volunteering to lead the writing of this chapter! Could you please organize a kick-off meeting for this chapter (example: https://github.com/HTTPArchive/almanac.httparchive.org/issues/3603#issuecomment-2064351177) to organize the writing of the chapter? 

Furthermore, it would be helpful if you and all other contributors (@svgeesus, @nhoizey, @eeeps , @foolip,@nucliweb,@MichaelLewittes) could join the slack channel of the HTTPArchive (https://join.slack.com/t/httparchive/shared_invite/zt-2hfkn28ts-~uXN4UGS0mXsKpzzhtZcow)

Thanks!

**Comment by scottjehl** [comment]
I'd love to see included in this year's report if there's been any uptick in responsive video usage now that support has returned across browsers. That is, how many sites are using video source elements with media attributes and what sizes are they commonly serving? Happy to help if there's any way I can!

**Comment by nrllh** [comment]
Unfortunately, we currently have no authors for this chapter. Is anyone of you (@svgeesus, @nhoizey, @eeeps, @foolip, @nucliweb, @eeeps, @MichaelLewittes) interested in contributing to this chapter as an author?

**Comment by svgeesus** [comment]
Unfortunately I am overcommitted right now, so can't take this on.

**Comment by stefanjudis** [comment]
@svgeesus, @nhoizey, @eeeps, @foolip, @nucliweb, @MichaelLewittes, @turban1988

Hi friends! 👋 I am very excited about this and looking forward to collaborating with all of you! As I know, we're a bit late with the original deadline, so let's kick things off quickly (if possible).

To start off, I would like to schedule a 30-60 minute meeting to start the planning and brainstorming process. So please provide your availability here for the next two weeks: https://doodle.com/meeting/participate/id/erMwP4kd

_I checked the present timezones and choose options in the european evening that should work for the US_.

Also, here is an agenda for what we might want to discuss on the kickoff call: https://docs.google.com/document/d/11lk8wSjs9PQXlWhv1FYeDynhrBxQNOUza85fjC5oB1k/edit (please request access). Feel free to add points — because I haven't led any Web Almanac related activities so far. 😅

The goal of the meeting will be to quickly get to know each other, set new deadlines and define our preferred workflow.

Speaking of the chapter content: I'll summarize all statistics and data points from the previous year in the gdoc above. Ideally, you could give some thought on which metrics you'd like to drop / adjust but also what new things we should add. :) 

Also a gentle reminder to join the #web-almanac-media channel on Slack (https://join.slack.com/t/httparchive/shared_invite/zt-2lx22qow3-pkcEJltSqtyP9_86V4uTZQ)

**Comment by nhoizey** [comment]
Thanks @stefanjudis for taking the lead! 🙏

**Comment by stefanjudis** [comment]
@nhoizey @eeeps @nucliweb @MichaelLewittes 

Thank you for filling out the doodle. We had a very clear winner and it's next week Thursday 11 AM GTM - 7 (SF) / 2PM GTM -4 (NYC) / 8 PM GMT+2 (Berlin). 🎉

@svgeesus @foolip @turban1988 

If you want to join please let me know and I also invite you. :) 

----

The folks joining the Kick-off call already have access to [a living document](https://docs.google.com/document/d/11lk8wSjs9PQXlWhv1FYeDynhrBxQNOUza85fjC5oB1k/edit?usp=sharing) that we'll use going forward. If someone wants to have access, too, just request it via Google. :) 

Looking forward to catching up with you all!

**Comment by svgeesus** [comment]
I just filled out the doodle

**Comment by stefanjudis** [comment]
Hey friends, I'm a bit late — sorry for the slight delay but here's a summary of what we discussed in our kick off call and how we'll proceed. Thank you @nhoizey @eeeps @MichaelLewittes @svgeesus for attending the kick off call.

And FYI @foolip @nucliweb. 

__1. PROJECT MANAGEMENT:__ We decided that we'll use this Github issue for project management. So you'll hear from me here about anything timeline and task related. Actually content discussions will happen in the existing Google Doc ([request access if you don't have it yet](https://docs.google.com/document/d/11lk8wSjs9PQXlWhv1FYeDynhrBxQNOUza85fjC5oB1k/edit)).

__2. DATA SOURCE:__ As we're late and the latest data set was already aggregated we decided that we'll primarily work off the last Almanac's Media Chapter. We try to keep it lean for now and will get into newly added data points if there's time and capacity.

<details>
  <summary>Possible new data point ideas</summary>
<ul>
<li><a href="https://github.com/HTTPArchive/almanac.httparchive.org/issues/3596#issuecomment-2123419767">Scott Jehl</a>: I'd love to see included in this year's report if there's been any uptick in responsive video usage now that support has returned across browsers. That is, how many sites are using video source elements with media attributes and what sizes are they commonly serving?</li>
<li><a href="https://github.com/HTTPArchive/almanac.httparchive.org/issues/3596#issuecomment-1979035386">Chris Lilley</a>: Then the "various ways they are encoded" becomes a much more tractable "look for CICP in images" and I suggest this metric for the 2024 Media survey. CICP is used in PNG, JPEG-XL and AVIF (that I know of, maybe others)</li>
<li>Stefan Judis: is loading=lazy a thing yet. Are libraries adopting this convention already?</li>
<li>Nicoloas Hoizey: Maybe we could add (next year?) details about which types are used in <source>s, in which order. (I've seen type switching with JPEG first… 😅)</li>
<li>Nicoloas Hoizey: The number of <source>s for art direction?</li>
<li>Nicoloas Hoizey: whether the latest <source> is useful or <img srcset sizes> would be enough, for both use cases (another frequent mistake)?</li>
</ul>
</details>

__3. DATA ACCESS:__ For the people that want to crunch data please get yourself into the `HTTPArchive GCP project` by reaching out to Christian. [More info in the HTTP Archive slack](https://httparchive.slack.com/archives/C016QLMT0BZ/p1716463138955289).

I just did and @eeeps did so too.

__4. NEW / SAME SCHEDULE:__ When looking at the set dates we're super late. We missed the first three points but I think we will catch up to hit the following.

- _Validate resultes_ 
  - 📆 August 15 Query Metrics & Save Results  — 🔑 Analysts have queried all metrics and saved the output.
- _Draft content_
  - 📆 September 15 First Draft of Chapter — 🔑 Authors  has written the chapter.
  - 📆 October 10 Review & Edit Chapter - 🔑 Reviewers & Editors have processed the the chapter.
- _Publication_
  - 📆 October 15 Chapter Publication (Markdown & PR) — 🔑 Authors has converted the chapter to markdown and drafted a PR.
  - 📆 November 1 Launch of 2024 Web Almanac 🚀

------

As agreed, to come back on track and make Aug 15, the analysts (@eeeps @foolip @nucliweb) have to evaluate if [all the queries from 2y ago still work](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/media). Eric offered to show me and possible others the way around to accessing and crunching all the data. Here's another doodle. 👇

https://doodle.com/meeting/participate/id/erMPW6Kd

_So far I think it'll be only Erik and me so I'll pick some times that are a bit later in the European time zone._

If we then still have time, we'll evaluate if / how new metrics could be added on the June data set.

**Comment by stefanjudis** [comment]
Hey friends, @eeeps and I just had our first big query session. The queries from two years ago seem to work 🎉, and we made a game plan. 

Looking at the deadline of finishing data crunching by Aug 15, **we probably won't make it but I'm targeting Sep 1** to have run all the queries and put the results into the official HTTP Archive Google Sheet. **We're primarily reusing the existing queries, and if time allows, Eric will look into adding more or query adjustments.**

After the data is done, I'll share the writing progress early to receive feedback early. You can expect me to hand over a fairly rough draft. 🫣

@nhoizey @eeeps @MichaelLewittes @svgeesus @foolip @nucliweb

**Comment by foolip** [comment]
I am going on parental leave, which is great, but unfortunately that means I won't be able to contribute to this effort at all.

**Comment by y-guyon** [comment]
Hi all, I would like to suggest a precision to the next ["Media - Bits per pixel by format"](https://almanac.httparchive.org/en/2022/media#bits-per-pixel-by-format) section of the Web Almanac. I referred a lot to that great resource for meaningful image codec performance comparisons so far, but the current version aggregates all image sizes, making the results hard to draw conclusions from.

For example .jpg is listed with a median 2.1bpp, whereas images between 1 and 2 megapixels should be closer to 1.3bpp.  
Would it be possible to split the results into a few buckets based on image dimensions? Categories such as `0 to 1 MP`, `1 to 2 MP`, `2 to 4 MP` and `4+ MP` would already be amply useful for the Chrome team.  
Please find Philip's demo SQL snippet at https://gist.github.com/foolip/34ed26159b17db30abbbe4890200da36.

Sorry for not having more time to contribute on this project and thanks everyone for the efforts here.  
Let me know if this request should be recorded in a different thread.

**Comment by stefanjudis** [comment]
@y-guyon Thanks for proposing another way to look at the data. We might look into it, but we're pretty stretched thin and decided to go with the existing metric set, primarily. :)

**Comment by stefanjudis** [comment]
@foolip @nucliweb @eeeps @scottjehl

I was able to reuse most of the queries and the majority of data points from 2022 are now available for 2024. With that we almost caught up with the data aggregation deadline of Aug 15.

You can find the queried data [here](https://docs.google.com/spreadsheets/d/1Q2ITOe6ZMIXGKHtIxqK9XmUA1eQBX9CLQkxarQOJFCk/edit?usp=sharing).

And here's the opened PR: #3738

Some queries are still running and I'll query / refine more once @eeeps is back to from his deserved vacation. 

@svgeesus @nhoizey @eeeps @MichaelLewittes

**I'll start drafting the chapter and plan to have something ready until Sep 15**

**Comment by stefanjudis** [comment]
@svgeesus, @nhoizey, @eeeps, @MichaelLewittes

Heads up: I'm a bit behind schedule, but I'm working hard to have the rough draft done by Sunday, October 6.

I know it's a short time frame and notice, so if you can, it'd be wonderful if you could review and provide feedback at the beginning of next week. :)

**Comment by svgeesus** [comment]
> I know it's a short time frame and notice, so if you can, it'd be wonderful if you could review and provide feedback at the beginning of next week. :)

Sure, although when I looked just now the image color space section was just TODO and might get deleted?

**Comment by eeeps** [comment]
@svgeesus see my questions here: https://httparchive.slack.com/archives/C017HPKG614/p1726609944124949?thread_ts=1725968488.150269&cid=C017HPKG614

**Comment by stefanjudis** [comment]
@svgeesus @nhoizey @eeeps @MichaelLewittes @nrllh 

> Sure, although when I looked just now the image color space section was just TODO and might get deleted?

That's, unfortunately, correct. When talking to Eric we agreed that I'm not the best right person to analyze or write about this topic.

And to be honest, I'm struggling fairly bad because it takes way more time than what I thought I agreed on. When agreeing to participate in the Media chapter, I understood that my role would be "writing" the chapter with analyzed and prepared data. But unfortunately, as we're all stretched very thin and when discussing things, I became the lead, analyst and primary author of the chapter. 

Until now, I've spent hours worth a work week on this (I'm self-employed) and because I've no strong data analysis / database background I must also admit that I haven't been the right person in the first place. So far, I've "just" reused and changed the existing queries but can't guarantee that the results are accurate — this alone took me several days.

The sad part is, that it will take at least another few days to write and finish the chapter and there's probably at least still a day worth of busy work to format everything required. As a result; in the current state and without additional help it will be a "poorer" chapter than the one 2y ago which makes me very uncomfortable.

Then, I wanted to push the project forward this weekend but life happened. 

Now, I've come to realize that I can't handle all this alone. **If someone can help out with busy work and writing, we might be able to reach an acceptable state to meet the deadline, but right now I'm not confident I'll make it in time.**

I'm terribly sorry for having underestimated all the work thinking I could handle it. :/

**Comment by stefanjudis** [comment]
@eeeps @nrllh @turban1988 @ldevernay

I've some great news! 🎉 @eeeps decided and might be willing to pick up the work done so far. :) Thank you, Eric!

The current status of the project is:

- 90% of the data is queried and in the google sheet
  - some sections that were over my head are still missing
  - most of the graphs aren't in the correct style
- I started drafting the chapter but didn't make it very far
  - the article includes screenshots and most data points

Because I aligned with Eric, I think he's aware of still needs to be done and it's up for him to decide how detailed this year's media chapter will be.

Apologies again for not delivering here and that I won't be able to commit any more time to this year's WA. 

Good luck, Eric! I'm sure you'll rock it.

**Comment by svgeesus** [comment]
Dropping this here because there is no Media 2025 issue yet.

Media 2024 has a section [**GIFs, animated and not**](https://almanac.httparchive.org/en/2024/media#gifs-animated-and-not). It would be nice next year to also have a **PNG, animated and not** section. Animated PNG is detectable by the presence of an [`acTL` chunk](https://www.w3.org/TR/png-3/#acTL-chunk).

[pngcheck](https://github.com/pnggroup/pngcheck) can be used to detect this.
