### ISSUE TITLE
Create templates for content pages

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#45]
We don't have chapters written yet but now would be a good time to create the infrastructure for them so we can just drop in the content when they're ready.

I'm working with a designer to create the look and feel, which should be ready by July. Meanwhile we can get started on the backend routing and templating in preparation.

We should create the following templates:

- [x] rename the splash page at index.html to splash.html and update main.py
- [x] create a new index.html for the post-launch home page, stub things like navigation and introductory text
- [x] create /2019/outline.html where we show a table of contents for all chapters
- [x] create /2019/chapter.html as a template for each chapter
- [x] create /2019/methodology.html to provide technical info about our test methodology
- [x] create /2019/contributors.html to acknowledge everyone who contributed to the project

The Almanac is an annual report and I expect to do this again next year, so we should be proactive and separate the annual content from the static content. In this case, the home page is static to the project while things like table of contents, chapters, methodology, and contributors may change year to year. These should all be organized in a 2019 template directory.

The contributors page will be based on the data in [this sheet](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/view#gid=770177464). It might be a good idea to create a JSON metadata file of all contributors and generate this page dynamically. This way we can also dynamically add authors/reviewers on the bylines of their respective chapters.

Any volunteers from @HTTPArchive/developers  who can take part or all of this issue?

**Comment by MSakamaki** [comment]
I part want to help.

Isn't it a problem to create a public web API use Google SpreadSheet script?

I made the next simple script. (I can not add this script to the original because I have no authority)
https://gist.github.com/MSakamaki/795b4c947fb0fdfc8e41d320e6e5ddc1

This points to my sheet where I copied the contributors page.
https://docs.google.com/spreadsheets/d/1DB0dhdgRiWfAeH5gTEd7nd3zsEuaNCMqp0gA1IGVzUA

When you hit the following API, you get json of name and hyperlink.
https://script.google.com/macros/s/AKfycbzuHDBRkaOlOi_iioNVKYQxVpQ4mZJy2V8xVS_l9FJM0eF3zhPq/exec

If there is no problem, we will start producing json API including the role.

**Comment by anoblet** [comment]
I can take care of the scaffolding

**Comment by rviscomi** [comment]
To clarify, I meant using a server side JSON file to maintain the contributors list. The Sheet was just an example of the current list 🙂

**Comment by MSakamaki** [comment]
@rviscomi 
Oh, I understand. Thank you for your explanation!

**Comment by rviscomi** [comment]
The templates exists, but we still need to write content for them. We can do that in follow-up issues.
