### ISSUE TITLE
Add Apache license info to page footer

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#532]
Change

> Copyright © 2019 Web Almanac. All rights reserved.

to

> Copyright © 2019 Web Almanac. Licensed under [Apache 2.0](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/LICENSE).

cc @brucelawson

**Comment by bazzadp** [comment]
This has just been deployed to production and was going to close this but looks like some issues:

Desktop is missing a space:
![image](https://user-images.githubusercontent.com/10931297/69576921-31ff2480-0fc5-11ea-9eea-8135cd97d16a.png)

Mobile has the licence over to the right:
![image](https://user-images.githubusercontent.com/10931297/69576961-46432180-0fc5-11ea-85ec-55f815e61d65.png)

Both seem to be due to the use of `display: flex` for `.copyright` class and removing that fixes it so gonna go ahead and do that. Shout if you see a better way of fixing this.
