### ISSUE TITLE
i18n - `lang` attribute usage in titles are incompatible with the chapter toc

### ISSUE THREAD

**Issue by borisschapira** [HTTPArchive/almanac.httparchive.org#656]
In some headings, I need to keep english words (because we usually don't translate them in French). For example, `Le <i lang="en">lazy loading</i> natif`.

If I do that in the markdown template, in a title:

```
## Le <i lang="en">lazy loading</i> natif
```

The script that generates the chapter table of content doesn't keep it and generates a strange anchor: 

```
<li>
    <a href="#le-i-langenlazy-loadingi-natif">Le lazy loading natif</a>
</li>
```

To fix the content, we would need to amend this line, in order to get the `innerHTML` instead of the textContent.

https://github.com/HTTPArchive/almanac.httparchive.org/blob/05862f757558393ee8ce7fb6efca737e603b831a/src/tools/generate/generate_table_of_contents.js#L23

and authorize HTML content in toc.html for the title…

To fix the anchor, I think it's relative to the markdown generation in `generate_chapters.js`, I don't think we could fix this easily.

**Comment by bazzadp** [comment]
Can't we just change it to a `<h2>` element? That's what we do when we want to use other complex HTML within markdown tags (e.g. images and tables are often entered in markdown as raw HMTL)?

**Comment by bazzadp** [comment]
Ah ignore me. It's generating fine in the main article HTML, just not in the ToC.

**Comment by bazzadp** [comment]
For the anchor tag, these are auto generated by [showdown](https://github.com/showdownjs/showdown/) and there doesn't seem to be a way to strip these our (there is a way to [pre-define the anchor tag but requires some customisation](https://github.com/showdownjs/showdown/issues/458) so not worth it IMHO).

What we can do, however is add this to [`remove_unnecessary_markup.js`](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/tools/generate/remove_unnecessary_markup.js)`, as it's very unique, and we have precendence for this sort of hackery in that file:

````js
html = html.replace(/le-i-langen/g, '');
````

It's not perfect as still leaves the trailing `i` (`loadingi` rather than `loading`):

```html
-              <a href="#le-i-langenlazy-loadingi-natif">Le lazy loading natif</a>
+              <a href="#lazy-loadingi-natif">Le lazy loading natif</a>
```

but it's a good bit better, and I think trying to capture that extra `i` with a similar regex will be too error prone.

So @borisschapira , I suggest we either:

1. remove this `<i lang="en">` element from the heading (not ideal - but it's defined immeadiately after in the paragraph) and close this issue.

or

2. If you are happier with above then I'm happy to accept a PR for the combination of your fix for the content and above to make the anchor a good bit less strange.

or

3. We accept your content change, and leave the strange anchor in place.

Thoughts?

**Comment by bazzadp** [comment]
Or we could add known exceptions as well (assuming this is very rare, so list will be small) with a catch all for those that are not entered explicitly:

```js
html = html.replace(/le-i-langenlazy-loadingi-natif/g, '');
html = html.replace(/le-i-langen/g, '');
````

**Comment by borisschapira** [comment]
@bazzadp Hi! I prefer to remove the attribute from the header. I think it's the best trade-off against the cost of the alternatives you exposed. We could think about it again if we ever change the build tools (I wonder if Eleventy has this issue) but in the meantime, this will do the trick.

**Comment by bazzadp** [comment]
Yeah probably the simplest option. The others may be overkill.

**Comment by borisschapira** [comment]
Thanks @bazzadp, that's perfect!
