### ISSUE TITLE
Questions on workflows

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#803]
@rviscomi we currently have two project workflows for managing issues in GitHub:

1. [Web Almanac](https://github.com/orgs/HTTPArchive/projects) - an organization level workflow.
2. [2020](https://github.com/HTTPArchive/almanac.httparchive.org/projects) - a repo level workflow.

I've some questions on this:

- What is the reason for the two workflows?
- And when are we supposed to use each one?
- And why is one organizational level and one repo level?
 - What is the purpose of the workflow anyway? Is it primarily used to be able to look at the project board (which I don't use to be honest - prefer to keep the number of issues small and managable)? Because they both have the same steps at the moment (TODO - In Progress - Done) and auto move to each stage as items are opened and closed.
- Should we just go to one Workflow? Are labels the better way of managing 2019 verus 2020 issues?
- Can we rename the "Web Almanac" one to "Web Almanac - old" and the "2020" one to "Web Almanac" because [Organization level workflows don't play well with some of our Github Actions](https://github.com/peter-evans/create-pull-request/issues/243), not to mention choosing which one to use in these Actions is difficult!

**Comment by rviscomi** [comment]
I've renamed the org-level project to "Web Almanac 2019" to help disambiguate.

I'd like to maintain separate projects for each edition so it's clear whether the work is more urgent for the upcoming publication or lower priority maintenance. They can coexist so I thought the distinction was needed.

I created the 2020 project at repo-level because I think it's scoped almost entirely to this repo. There may be things like custom metrics that touch the bigquery repo but those should be infrequent.

The purpose of assigning a project to issues/PRs is for me with my project manager hat on to organize things by what needs to get done / what's getting done / what's done. Last year I would go through the TODO list and triage, or nudge people sitting on tasks in progress. Automation should handle most of the bookkeeping for us, so it's not a huge burden.

If there's any maintenance work that is incompatible with the 2019 project, feel free to omit it.

**Comment by bazzadp** [comment]
OK but we can’t use org level workflows in GitHub Action pull requests. So choices are:

1. Don’t auto-set the workflow and manually set it, just before approving the auto-generated PR.
2. Using the 2020 workflow for these auto-generated PRs.
3. Setting up a new Workflow just for the automated PRs.
4. Try to guess the workflow to use based on whether editing a 2019 file or 2020 file.

Do you have any particular preference? We could always start with 1. for now (as commits are more likely to be for 2019) and then switch to 2. once the 2020 work kicks off in earnest.

**Comment by rviscomi** [comment]
It's ok to omit the project if there are incompatibilities. It's a convenience thing and not a must-have.
