### ISSUE TITLE
PWA 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#909]
# Part II Chapter 14: PWA

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @hemanth | @thepassle @jadjoubran @pearlbea @gokulkrishh @jaisanth @logicalphase | @bazzadp | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @hemanth

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1JjjwHNjEsF6fl4WNod6mOj-58IIDzg-el3wh36mV3nM/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/14_PWA
[~results-sheet]: https://docs.google.com/spreadsheets/d/1AOqCkb5EggnE8BngpxvxGj_fCfssT9sZ0ElCQKp4pOw/edit#gid=2077755325

**Comment by logicalphase** [comment]
I'm still really hoping to author or co-author this section. The last three years I've been actively involved in introducing PWAs to the wider web communities. So along with last year's references I've developed a lot of reference material on adoption.

**Comment by jadjoubran** [comment]
Also interested in peer reviewing this chapter 👍

**Comment by thepassle** [comment]
I'd also be interested in doing review work here 🙂

**Comment by obto** [comment]
@hemanth thank you for agreeing to be the lead author for the PWA chapter! As the lead, you'll be responsible for driving the content planning and writing phases in collaboration with your content team, which will consist of yourself as lead, any coauthors you choose as needed, peer reviewers, and data analysts.

The immediate next steps for this chapter are:

1. Establish the rest of your content team. Several other people were interested or nominated (see below), so that's a great place to start. The larger the scope of the chapter, the more people you'll want to have on board.
2. Start sketching out ideas in your [draft doc](https://docs.google.com/document/d/1JjjwHNjEsF6fl4WNod6mOj-58IIDzg-el3wh36mV3nM/edit?usp=sharing).
3. Catch up on [last year's chapter](https://almanac.httparchive.org/en/2019/pwa) and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to get a sense for what's possible.

There's a ton of info in the top comment, so check that out and feel free to ping myself or @rviscomi with any questions!

@thepassle @jadjoubran @logicalphase @pearlbea I've put you down as reviewers for now, and will leave it to @hemanth to reassign at their discretion

@abraham @tpiros we'd still love to have you contribute as a peer reviewer or coauthor as needed. Let us know if you're still interested!

**Comment by hemanth** [comment]
Awesome @rviscomi! 
Looking forward to work will all the co-authors and reviewers, PWA FTW!

**Comment by logicalphase** [comment]
@hemanth I'd be happy to co-author this. I've got the time and significant experience with PWAs. Just let me know. Cheers.

**Comment by hemanth** [comment]
Sure @logicalphase let us discuss, there was one more purpose who was interested too.

**Comment by hemanth** [comment]
For the **July 13th** checklist completion we have:

Author + Analysts: @hemanth 
Reviewers: @thepassle @jadjoubran @logicalphase @pearlbea

Reviewers: please confirm with a thumbs up to this comment, if you are still interested in reviewing, thank you!

**Comment by hemanth** [comment]
Meanwhile, for July 20th item on the checklist, I have added a [potential chapter outline](https://docs.google.com/document/d/1JjjwHNjEsF6fl4WNod6mOj-58IIDzg-el3wh36mV3nM/edit#heading=h.vqdmpb884vdu) please have a look and leave a comment on the document or in the issue here, thank you! 

//cc Reviewers: @thepassle @jadjoubran @logicalphase @pearlbea

**Comment by logicalphase** [comment]
Outstanding @hemanth I'm looking forward to working with the you and the team. Will review your materials, and reply. Please let me know if you need anything else right now.

**Comment by obto** [comment]
Hey @hemanth, looks like things are moving along pretty smoothly. Is there anything you need from me to keep things moving forward, and have the chapter outline and metrics settled on by the end of the week?

Also, can you remind your team to properly add and credit themselves in your chapter's Google Doc?

**Comment by thepassle** [comment]
> Also, can you remind your team to properly add and credit themselves in your chapter's Google Doc?

Looks like I need some permissions — I requested them in the google doc. I imagine this'll be true for the other reviewers, too. 🙂 Fyi

**Comment by obto** [comment]
You should get access shortly :)

**Comment by tungpatrick** [comment]
Hey @obto @hemanth! I would love to help as an analyst, however, I am actually a fairly new 'analyst' and am very new to HTTP Archive. Will this be a problem? I definitely think this is quite grand, so I wanted to ask before I partake in such a role.

**Comment by tpiros** [comment]
Since I'm involved in the Media and Jamstack chapters, I will withdraw from this one if that's OK :) (or at least I'll unsubscribe if I'm not needed anyway :) )

**Comment by tungpatrick** [comment]
Hey @obto @rviscomi! I noticed that I've been added as an analyst for this chapter. Thank you for allowing me to help. However, as I have mentioned, I am very new and am not really familiar with the HTTP Archive dataset. I find this to be a great experience for me, but I'm not sure if I'm qualified on my own as the analyst for this chapter. With that being said, I am very grateful for having this opportunity, so I was wondering if there would be any way for me to learn what's in the dataset or allow me to explore it without incurring too much cost (so that I can help to my best effort).

**Comment by hemanth** [comment]
Hey @tungpatrick you can give it a shot and you aren't alone, we can take assistance from folks who have played this role before. If you are willing I can add you to the list. The [Analysts'-Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide) talks in detail about it, also have a look at how it was done in the previous year.

Given that @logicalphase has experience in illustration and content writing, I would vouch for him to be the co-author, as we look forward to some awesome SVG animations for our chapters! 😉

**Comment by logicalphase** [comment]
I'm glad there's no pressure, @hemanth 😁

**Comment by gokulkrishh** [comment]
@hemanth @rviscomi  I can help in reviewing the content.

**Comment by jaisanth** [comment]
@hemanth  I'm interested in being a reviewer, not sure if this is already filled up :-)

**Comment by tungpatrick** [comment]
Hey @hemanth! I think I have actually already been added as an analyst for this chapter. I am definitely willing and would love to help. I just don't want to be a burden to the team haha. I have taken a quick look at the 2019 Almanac, which is a main reason why I have wanted to volunteer. Hopefully after getting a chance to explore the dataset, I'll be more helpful. Again, thanks for letting me participate!

**Comment by hemanth** [comment]
@gokulkrishh and @jaisanth Added your names to the reviewers' list, thanks for volunteering! 

@tungpatrick Thank you! Also, please have a look at the milestones and feel free to ask your quires on this thread.

**Comment by obto** [comment]
@tungpatrick we're excited to have you! @bazzadp just made a great post about the best way to get started i think you'd find very helpful https://github.com/HTTPArchive/almanac.httparchive.org/issues/914#issuecomment-659205330

Do make sure to join the [`#web-almanac`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) slack so Paul can invite you to the Analysts channel. It's a great place to ask any questions you may have :)

**Comment by logicalphase** [comment]
@hemanth Just in time:, Chrome 84 added a slew of [animations](https://twitter.com/slightlylate/status/1283807707007352832?s=19) support. Example:  https://developers.google.com/web/updates/2020/07/nic84#web-animations

cc: @obto

**Comment by tungpatrick** [comment]
Hey @hemanth! I sent a quick DM on slack, but I feel like that might not have been the best place to reach out to you, so I'll type here. I'm not really sure how to proceed at the moment. So I'm not sure about the procedure for the web almanac as I'm fairly new to this whole thing. I can see that you have drafted up an outline for the chapter, so yay! But my question now is... am I supposed to generate a whole bunch of queries that you can use (given the outline)? Or would there be a list of ‘Metrics’ that I should look into to see if I can query it?

Oh, and another quick question! How much of last year's queries do you think can be reused this year? Do you think we can just 'copy & paste' (with some modifications) from last year?

Thank you so much in advance!

**Comment by rviscomi** [comment]
@tungpatrick once the outline has been finalized, the next step is for you to work with the authors to understand what metrics they need to substantiate the content. Ask questions in the doc if any content in the outline is unclear. Use the "Metrics" section of the doc to compile the list of metrics that would need to be queried. Most importantly, identify which metrics are candidates for [custom metrics](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide#almanac-custom-metrics-and-udfs), which collect the data at runtime using JS APIs as opposed to statically analyzing the HTML responses in BigQuery (which is much more expensive). Any custom metrics needed for this chapter must be implemented by the 27th so that they're in place before the August 1 crawl begins.

**Comment by tungpatrick** [comment]
@rviscomi Thank you for the clarification. Unfortunately, I think it would be a little difficult for me to implement any custom metrics, but I'll reach out for help if needed.

@hemanth I'd love to schedule a time with you to understand what metrics you'd like to use for the content of this chapter.

**Comment by hemanth** [comment]
Sorry @tungpatrick missed your ping on slack, sure let us catch up and discuss further.

**Comment by rviscomi** [comment]
@tungpatrick that's ok, let's see if any custom metrics are needed (maybe none) and I'm sure we could find another analyst to help if needed. Please ping me or @paulcalvano if that's the case.

**Comment by obto** [comment]
@tungpatrick @hemanth If there are any custom metrics you need, let me know by EOD tomorrow. I'm working on implementing a large amount of them right now ([PR here](https://github.com/HTTPArchive/legacy.httparchive.org/pull/172)).

**Comment by hemanth** [comment]
Sure, thanks @obto!

**Comment by rviscomi** [comment]
@logicalphase @pearlbea @gokulkrishh @jaisanth have you all had a chance to contribute to and review the [planning doc](https://docs.google.com/document/d/1JjjwHNjEsF6fl4WNod6mOj-58IIDzg-el3wh36mV3nM/edit?usp=sharing)? Please request edit access to make sure you can comment and others can @ you.

**Comment by logicalphase** [comment]
I've reviewed  the planning doc. Looks good. I think for metrics I like
usage [I've used built within], I'm wondering how PWAs get tracked,?
Manifest? I've got a list of a few sources I've been researching through,
and comfortable with any of the background sub chapters as listed in the
planning outline.  Should we split them out or assign to me what works best
for you?

**Comment by gokulkrishh** [comment]
@rviscomi @hemanth Sent a request for the edit access. Planning to review over this weekend.

**Comment by obto** [comment]
@hemanth @tungpatrick for the two milestones overdue on July 27 could you check the boxes if:

- the [outline][~outline] has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics][~custom] have been created and you've created a [draft PR][~draft_pr] to track which feasible metrics have had their [queries][~queries] implemented (we've updated the milestone description to clarify this)

Keeping the milestone checklist up to date helps us to see [at a glance][~glance] how all of the chapters are progressing. Thanks for helping us to stay on schedule!

[~custom]: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md
[~draft_pr]: https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis
[~glance]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989
[~outline]: https://docs.google.com/document/d/1JjjwHNjEsF6fl4WNod6mOj-58IIDzg-el3wh36mV3nM/edit
[~queries]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/14_PWA

**Comment by tungpatrick** [comment]
Hey team! Due to some personal reasons, I have removed myself from the web almanac and from the team. Sorry in advance if this causes any problems to the team. Thanks for letting me have the chance to volunteer!

**Comment by rviscomi** [comment]
Sorry to see you go @tungpatrick but completely understand.

@hemanth are you [still interested](https://github.com/HTTPArchive/almanac.httparchive.org/issues/909#issuecomment-657289214) in being an analyst for this chapter? I also see @thepassle listed in the [doc](https://docs.google.com/document/d/1JjjwHNjEsF6fl4WNod6mOj-58IIDzg-el3wh36mV3nM/edit?usp=sharing) as an analyst but I don't see any discussion of that happening in this issue, so not sure if that's intentional. Could you update https://github.com/HTTPArchive/almanac.httparchive.org/issues/909#issue-646592503 and the doc with the correct analyst assignments?

Also as @obto mentioned, this chapter is overdue on a couple of milestones, so it'd be great to get these sorted out ASAP to stay on schedule. Thanks!

**Comment by thepassle** [comment]
Not sure who put me there as analyst, I signed up as a reviewer 🙂

**Comment by hemanth** [comment]
AFAIR @thepassle wasn't on the analyst list.

@tungpatrick had singed up earlier, but looks like we were lost in translation.

@obto Looks like we have slipped a bit on the deadlines? Also, for custom metrics, we should be able to get insights on the APIs that are being used in the serviceworkers that we parse?

**Comment by hemanth** [comment]
We need to decided on this sooner, maybe should I add a label requesting analyst? 

@rviscomi @obto We had a slack channel for PWA discussions, right?

**Comment by rviscomi** [comment]
> We need to decided on this sooner, maybe should I add a label requesting analyst?

Yes, good idea. You can also reach out on the #web-almanac-analysts to see if anyone is available. Or if you're interested in taking on the role, some of us can help with the onboarding.

> @rviscomi @obto We had a slack channel for PWA discussions, right?

Not a channel but I did start a group chat to discuss this: https://httparchive.slack.com/archives/G0181NNKEJH/p1596215461000600

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1AOqCkb5EggnE8BngpxvxGj_fCfssT9sZ0ElCQKp4pOw/edit#gid=2077755325

**Comment by hemanth** [comment]
@obto @rviscomi I would vote to tick the checkboxes with the data we have. 

Me and @logicalphase should probably get started with the content we have a month and couples of days to go and about 5-6 chapters to cover.

**Comment by bazzadp** [comment]
@hemanth / @logicalphase I can probably help
out and run some of the queries for you.

However the Metrics section of [your document] is looking very bare!

What would be great is if you could review [the spreadsheet from last year](https://docs.google.com/spreadsheets/d/19BI3RQc_vR9bUPPZfVsF_4gpFWLNT6P0pLcAdL-A56c//) and let me know:
1) Which tabs you think would be useful to have the stats rerun for this year. Maybe all of them?
2) Which stats are missing and some detail of what exactly you’re looking for and I can let you know if they are feasible.

@tungpatrick I don’t know if your situation has changed, or if you’d like to be involved again as a co-analyst now you have someone to help guide you through this? If so let us know as happy to help you!

**Comment by hemanth** [comment]
Thanks for pitching in @bazzadp!

> Which tabs you think would be useful to have the stats rerun for this year. Maybe all of them?

Yes.

> Which stats are missing and some detail of what exactly you’re looking for and I can let you know if they are feasible.

We were looking into way to figure out if we can pull stats about certain feature set and their usage, like `BackgroundSync`, `PeriodicSync`, offline analytics and likes.

I noticed @jaisanth is an analyst for JavaScript and maybe he can help us too?

**Comment by bazzadp** [comment]
> We were looking into way to figure out if we can pull stats about certain feature set and their usage, like `BackgroundSync`, `PeriodicSync`, offline analytics and likes.

Some of these may be tracked in the `blink_usage` table. This is a list of 4,163 features that Chrome records websites using as they are crawled including `PeriodicBackgroundSyncRegister` and `PeriodicBackgroundSync`. [Full list of tracked features here](https://docs.google.com/spreadsheets/d/10qKqQF-7DE_ncgwAgtEnBcpANRBIVt0zNrlVl32ePGM/edit?usp=sharing) if you can spot any others that might be useful.

Alternatively, one of the stats they ran last year was [11.06](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2019/11_PWA/11_06.sql) which scanned the first HTML page (e.g. `index.html` in case of inline `<script>` tags) and also any Script files for `beforeinstallprompt` to see who was using that. We could do something similar to search for `sync.register` and the like. It's not as accurate and prone to false positives, and even missing some stats if you don't have a specific phrase to search for, but it does allow use to hunt for things not tracked. The other problem with that is it's incredibly expensive to query as it's 24TB of data as it's basically scanning all the response bodies for all files. @rviscomi would it be possible to create an `almanac.response_bodies_scripts` table of just the initial HTML (incase of inline `<script>` tags) and `script` resources to cut this down as much as possible? Or maybe should have `almanac.response_bodies_firsthtml` and `almanac.response_bodies_scripts`? If not then we should try and query everything we need in one go, rather than in multiple queries to reduce usage.

As to offline analytics we couldn't test if they are fired but using either of above methods could search for them. Can't see anything in the `bleak_features` table for that myself so think it would be searching for things like `workbox-google-analytics` so would need help as to what search phrases to look for.

**Comment by bazzadp** [comment]
BTW HTTPArchive recently launched a [capabilities dashboard](https://httparchive.org/reports/project-fugu#) including stats you might be interested in like:
- [Get Installed Related Apps](https://httparchive.org/reports/project-fugu#getInstalledRelatedApps)
- [Periodic Background Sync Register](https://httparchive.org/reports/project-fugu#periodicBackgroundSyncRegister)
- [Periodic Background Sync](https://httparchive.org/reports/project-fugu#periodicBackgroundSync)

Just as long as we don't repeat too much of the Capabilities chapter.

**Comment by hemanth** [comment]
@bazzadp the legends and graphs seems bit out of sync? [Or the legend isn't considering the second decimal point]

![image](https://user-images.githubusercontent.com/18315/92982146-bf770c80-f451-11ea-8f9c-f92acc78b5f0.png)

This means `0.00003%`?

**Comment by bazzadp** [comment]
> @bazzadp the legends and graphs seems bit out of sync? [Or the legend isn't considering the second decimal point]

Not sure what you mean? Do you mean because the legend is only going to 1 decimal place whereas the numbers (as shown by the axis) are so small that means it shows 0.0?

When [we looked last year](https://almanac.httparchive.org/en/2019/pwa#service-workers) only 0.44% of pages installed a service worker - though because some big names did, that meant that 15% of page views used a service worker. Would be great to have some examples of big names to explain that discrepancy more this year!

Looking at PeriodicBackgroundSync and PeriodicBackgroundSyncRegister only 1 site (https://uhcitp.in/) uses it according to the blink_usage table which is why it's just 0.00003%. Not sure that's right to be honest! Expected it to be small but just 1 site seems too small to me. Will have another look via regexing the JavaScript once we have the stats tables for that (Rick's working on these for us).

We're basically using the methodology described here: https://medium.com/dev-channel/progressive-web-apps-in-the-http-archive-614d4bcf81fe. Thomas was one of the co-authors of last years chapter. Some interesting ideas for further research in there too so you should have a read of that.

**Comment by hemanth** [comment]
> Not sure what you mean? Do you mean because the legend is only going to 1 decimal place whereas the numbers (as shown by the axis) are so small that means it shows 0.0?

Yes.

> Expected it to be small but just 1 site seems too small to me.
Me too, I have personally come across few more sties which use them! 

Nice article there, I also noticed `progressive_web_apps.web_app_manifests` query.

**Comment by bazzadp** [comment]
Yes that table (we just called it manifests) which contains the `manifests.json` and a `service_worker` table (which contains the servicework JavaScript code) is what I'm waiting to be created from the 2020 dataset (the August crawl data) to be able query this and then give you these stats. Know @rviscomi is already working on it so hopefully in next few days I'll be able to give you all the stats.

**Comment by ibnesayeed** [comment]
Now that @bazzadp is added as an Analysts, the second task's checkbox should be checked.

**Comment by bazzadp** [comment]
> Now that @bazzadp is added as an Analysts, the second task's checkbox should be checked.

Done.

**Comment by bazzadp** [comment]
@tomayac can you explain the low usage of [Periodic Background Sync Register](https://httparchive.org/reports/project-fugu#periodicBackgroundSyncRegister) and [Periodic Background Sync](https://httparchive.org/reports/project-fugu#periodicBackgroundSync)? Is this expected?

I've also found regular BackgroundSync and BackgroundSyncRegister which has a good bit more usage, but still not massive. Not sure what's the difference?

Row | yyyymmdd | client | id | feature | num_urls | total_urls | pct_urls | sample_url
-- | -- | -- | -- | -- | -- | -- | -- | --
2 | 20200801 | desktop | 745 | BackgroundSync | 243 | 5593642 | 4.34E-05 | https://goalkicksoccer.com/
4 | 20200801 | desktop | 1025 | BackgroundSyncRegister | 232 | 5593642 | 4.15E-05 | https://www.trivago.com.uy/
1 | 20200801 | desktop | 2930 | PeriodicBackgroundSync | 1 | 5593642 | 1.79E-07 | https://uhcitp.in/
3 | 20200801 | desktop | 2931 | PeriodicBackgroundSyncRegister | 1 | 5593642 | 1.79E-07 | https://uhcitp.in/
6 | 20200801 | mobile | 745 | BackgroundSync | 270 | 6347919 | 4.25E-05 | https://www.iamgujarat.com/
5 | 20200801 | mobile | 1025 | BackgroundSyncRegister | 262 | 6347919 | 4.13E-05 | http://miui.in/
7 | 20200801 | mobile | 2930 | PeriodicBackgroundSync | 1 | 6347919 | 1.58E-07 | https://uhcitp.in/
8 | 20200801 | mobile | 2931 | PeriodicBackgroundSyncRegister | 1 | 6347919 | 1.58E-07 | https://uhcitp.in/

**Comment by tomayac** [comment]
Maybe @jeffposnick as the author of the [web.dev article](https://web.dev/periodic-background-sync/) has more insights into how expected or not these results are, but it's definitely in-line low with what we see [on ChromeStatus](https://chromestatus.com/metrics/feature/timeline/popularity/2931).

The actual `periodicsync` events are expected to be low, since a lot of sites probably don't meet the required [site engagement thresholds](https://web.dev/periodic-background-sync/#getting-user-engagement-right) we have put in place, but registrations are independent from this.

**Comment by jeffposnick** [comment]
Yes, I think it just reflects legitimately low usage. Periodic background sync functionality is only available in PWAs that have been installed, for one thing, and that's a fairly high barrier.

**Comment by bazzadp** [comment]
Thanks @tomayac / @jeffposnick 

@hemanth @logicalphase (and also @thepassle @jadjoubran @pearlbea @gokulkrishh @jaisanth if interested) I've completed the queries and dumped a first cut of the results in [this year's PWA sheet](https://docs.google.com/spreadsheets/d/1AOqCkb5EggnE8BngpxvxGj_fCfssT9sZ0ElCQKp4pOw/) for you to have a look at.

As discussed previously, these are mostly based (stolen!) from @tomayac & @jeffposnick 's hard work last year (so I've kept the tab order in the Sheets roughly in-line with [last year's results sheet](https://docs.google.com/spreadsheets/d/19BI3RQc_vR9bUPPZfVsF_4gpFWLNT6P0pLcAdL-A56c/) so you can compare) but I have added a few that I thought might be interesting including:

- Some blink metrics I thought you might be interested in (some of which are discussed above).
- All lighthouse audits from the PWA category.
- Lighthouse PWA scores by percentile.
- I've included the 2019 Almanac stats (from 20190701) in some of the tables for ease of comparison as to how the landscape has changed since last years chapter.
- Details about how many Manifests and ServiceWorkers are out there - there's a lot more Manifests than SWs! That might be interesting to dig into why.
- Because so many pages without SW have Manifests, I've broken all the Manifests stats into "All pages" and "Service Worker" pages as thought it might be interesting to see the differences (not sure if you're ONLY interested in ServiceWorker pages for this chapter as depends on your definition of a PWA).
- I've delved into the `importscripts` use a lot more this year as, reading last year's chapter, was worried this was hiding a lot of usage. Please to say that, other than libraries, it looks to be very small.
- Listed the popular library scripts imported.
- Delved more into what Workbox package and methods are being used.

One important point is that my SQL has [NOT been reviewed yet](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1283) but the other analysts. So consider this an early look before you get the official signed off stats later in case I'm made lots of errors in it.

Still, I think it would be good for you all to dive in, see what you think of the stats, ask questions, and also let me know if there's any more stats you want not covered here. And if you're anyway familiar with SQL then please do like at my queries to see how we got this and/or suggest other stats to get.

Let me know your thoughts.

**Comment by hemanth** [comment]
Thanks a ton @bazzadp, I see the PR is now merged.

I guess it is time for @hemanth @logicalphase to start working on the draft!

**Comment by bazzadp** [comment]
Yup go for it. Let me know if you have any questions or anything else you want me to dig into but hopefully there’s quite a lot of stuff there for you to dig into!

Looking forward to see what you write!

**Comment by logicalphase** [comment]
Hey all. I've recently had surgery and been on the mend. I just need a few days this week to catch up on some things. But I'm ready to go after.

**Comment by rviscomi** [comment]
@logicalphase glad to hear you're recovering, and please take as much time as you need.

**Comment by hemanth** [comment]
@logicalphase Take care!

**Comment by romaincurutchet** [comment]
Hi,
Is there going to be a HTTP Archive table with all the PWA & Service Worker metrics?
Thank you.

**Comment by bazzadp** [comment]
Not sure what you mean? There’s many metrics pulled across from many of the tables. We don’t in general create new tables with specific queries for a specific subject, but instead share the queries and the results from those queries.

Saying that we did create a few helpers tables of the August data to list all manifests and service worker JavaScript to help with the queries but no plans to create those every month.

**Comment by romaincurutchet** [comment]
Hey, I was referring to this thread: https://discuss.httparchive.org/t/progressive-web-apps-in-the-http-archive/1401
In particular, I like the metrics under the section "Service Workers Analysis".

**Comment by bazzadp** [comment]
Yes that is basically the methodology we are following for this years chapter (Thomas wrote last years chapter and the queries he created for that are being reused for this years chapter with a few more).

We are currently analysing the results of this data now and will publish our thoughts later in the year. If curious you can see the SQL used and the results sheet of those queries from the links at the top of this issue.

**Comment by bazzadp** [comment]
Hey @hemanth / @logicalphase did you get a chance to look over the stats yet? Do let us know if you think that's enough info to write the chapter or if there are any other stats you think you'll need and I can look to see if possible.

P.S. Hope you're recovering from your surgery @logicalphase and don't feel pressured to reply if still dealing with that - your health is more important!

**Comment by hemanth** [comment]
Thanks @bazzadp! 

I went through the PWA Sheet and it as almost all the information required for the chapters under our radar.

Also, from our pervious discussions the metrics on `BackgroundSync` is as per the expectations right?

**Comment by bazzadp** [comment]
> Also, from our pervious discussions the metrics on `BackgroundSync` is as per the expectations right?

Yes it appears to be. If you are aware of any examples in the wild using this then feel free to ping me and can see if it’s in the data, but for now, it doesn’t appear to be used much at all! And particularly the periodic versions.

**Comment by obto** [comment]
@hemanth in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by hemanth** [comment]
Yes @obto 

That's great news, sorry was AFK for couple of days.

Will restart pawing at this and eager to see this go live too!

**Comment by hemanth** [comment]
@logicalphase @thepassle @jadjoubran @pearlbea @gokulkrishh @jaisanth

We should meet and have a quick discussion on the few of the steps we need to take to reach the finish line sooner.
I understand that we are in different timezones and it is hard to find the best time...but let me propose 7.30PM PST 11/08/2020, hope that sounds like a plan.

**Comment by hemanth** [comment]
@logicalphase @thepassle @jadjoubran @pearlbea @gokulkrishh @jaisanth 

The draft is ready for review please have a look and comment wherever it makes sense, have a look at the charts and let us know if they sound good or require additions or deletions. 

Shoutouts to @bazzadp for fine tuning the graphs (lot of graphs!) 🙏

**Comment by bazzadp** [comment]
@thepassle @jadjoubran @pearlbea @gokulkrishh @jaisanth @logicalphase any further comments on @hemanth 's draft?

Would be good to move this forward into converting this to Markdown but we should make sure you've all reviewed and fed back any commands before then as easier to manage the chapter in Google Docs initially.

**Comment by thepassle** [comment]
Sorry, I missed this. I'll take a look and dive in tomorrow 🙂

**Comment by gokulkrishh** [comment]
@hemanth @bazzadp Add a few suggestions via comments doc. Feel free to reject it if you feel it is not accurate. Awesome work on the doc people. Excited for the full report of web almanac 2020 and CDS 🤗

**Comment by thepassle** [comment]
Just went through the draft and left some comments 👍 Nice work so far

**Comment by bazzadp** [comment]
@hemanth did you get a chance to look over and address the feedback? We need to start converting this ti Markdown is we want to make the launch date in one week's time.

**Comment by hemanth** [comment]
@bazzadp I have addressed all the feedback comments, there is only one graph that's pending with more information, post which we must be good to convert it to markdown. 👍

**Comment by rviscomi** [comment]
@hemanth that's great! I'd recommend that you start on the markdown conversion now and leave a placeholder for the outstanding graph, for example you can use a Jinja comment:

```
{# TODO(analysts, authors): Add graph for the XYZ metric. #}
```

That way we can review the markdown in a PR while the data viz is pending. That should help keep this chapter on schedule while we wait.

**Comment by hemanth** [comment]
@rviscomi Are we using any specific tool or any text to md CLI tool do?

**Comment by rviscomi** [comment]
Whatever is easiest for you. Personally, I'll copy the plain text from the doc, paste it into a text editor, and manually add the markdown syntax. @bazzadp has also had some useful advice about the process [here](https://github.com/HTTPArchive/almanac.httparchive.org/issues/908#issuecomment-733957111) and [here](https://github.com/HTTPArchive/almanac.httparchive.org/issues/908#issuecomment-733963486).

**Comment by hemanth** [comment]
Had that as the second that, yeah, sounds like we are better off doing it manually, will start working on it.

**Comment by rviscomi** [comment]
Sounds great, thanks for working on it

**Comment by hemanth** [comment]
#1613 is ready with MD. 

//cc @rviscomi @bazzadp
