### ISSUE TITLE
Refactor inline commands from Generate Chapters workflow file into a script

### ISSUE THREAD

**Issue by ibnesayeed** [HTTPArchive/almanac.httparchive.org#962]
Currently, there are many inline commands in the [generate_chapters.yml](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/.github/workflows/generate_chapters.yml) workflow file that look repetitive and make the workflow file difficult to read. We can extract them out in a Shell script and call that script in the workflow steps as needed with appropriate arguments. This will also make these commands more testable locally as currently they can only run in the workflow environment.

**Comment by bazzadp** [comment]
Yes possibly we should do this. For testing locally this would definitely help. Getting these right was a big pain as had to run the Action so many times. However, due to the slight differences in each *nix OS, they really need to be tested on ubuntu.

Note that each line is not actually repetitive and there are slight differences but possibly they could be refactored to avoid duplication.

Note also that I'd NOT recommend running these locally much as part of a code commit (which is why I've not scripted them yet) as they will likely cause merge conflicts with other PRs since they change last updated timestamps and cache-busting query params, that multiple in-flight PRs may all look to edit at same time. So definitely would keep them out of `npm run generate`, hence why I was happy for them to be in linux commands.

**Comment by ibnesayeed** [comment]
While looking at those commands, I noticed successive `sed` piping, which can be optimized with a less known secret of `sed` that we can perform multiple actions (not even limited to just substitutions) in a single pass. This means the `sed` command will not be invoked as many times. Not that it is going to improve the performance in any substantial manner in this case, but is a cool thing nonetheless.

```
$ echo "Hello there" | sed 's/there/world/' | sed 's/w/W/'
Hello World
$ echo "Hello there" | sed 's/there/world/; s/w/W/'
Hello World
```

**Comment by ibnesayeed** [comment]
> Note also that I'd NOT recommend running these locally much as part of a code commit...

I would note here that some changes to the code base triggered by GH Actions do not propagate another action that would otherwise be invoked on that event. GitHub does this to avoid mutually reinforcing chains of workflows that will go out of hand and will run forever.

**Comment by bazzadp** [comment]
Re: the `sed` pipping we could do that. However using lesser known commands often make code less understandable with no real gain. Then again this code is pretty difficult to understand. I wrote it an have already forgotten what `sed 's!.*/!!'` does!

Re: your next comment, I’m less worried about GithubAction recursions than peoples PRs not being able to be merged because they have to fix merge conflicts every time another PR is merged.

**Comment by ibnesayeed** [comment]
> Re: the `sed` pipping we could do that. However using lesser known commands often make code less understandable with no real gain.

But then it educates people to make them a little more known! ;-)

> Then again this code is pretty difficult to understand. I wrote it an have already forgotten what `sed 's!.*/!!'` does!

I think this command is removing "something followed by forward slash". We don't necessarily have to use `/` as the delimiter in `sed`, we can use symbols like `|` or `!` to avoid unnecessary escaping. This is a handy trick when the pattern contains forward slashes, such as paths.

> Re: your next comment, I’m less worried about GithubAction recursions than peoples PRs not being able to be merged because they have to fix merge conflicts every time another PR is merged.

I didn't mean to change this behavior in this particular case. I just thought I would share this as a note to keep in mind in situations where it may matter.

**Comment by bazzadp** [comment]
@HTTPArchive/developers anyone with good shell scripting skills and/or GitHub Action skills fancy tackling this one?
