### ISSUE TITLE
Style dropdown lists

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#986]
Related to #985, existing dropdown lists like the year and language pickers use `select` and `option` elements to represent list items. These are styled natively by the UA:

![image](https://user-images.githubusercontent.com/1120896/86954544-2ad7f180-c124-11ea-940a-bd8c63fb3fae.png)

I'd like to see these better fit with the Almanac style by customizing the appearance of the dropdown lists.

@HTTPArchive/developers any ideas for how this could look or anyone interested to build it?

**Comment by sudheendrachari** [comment]
I would like to give this a shot, let me come up with a prototype with styles similar to dropdown in HTTP Archive. We can take a call based on that

**Comment by rviscomi** [comment]
Thanks @sudheendrachari great to have you working on this! A prototype sounds like a great first step.

**Comment by sudheendrachari** [comment]
I am no designer 😁 but here is what i could imagine and style these two dropdowns into:

Major changes: 
 - Reduced the rounded corners to only 5px radius (Completely rounded corners doesn't seem to fit well into dropdown style layout)
 - Instead of chevron added relevant icons for both
 - Instead of border, used background color to differentiate from other items in menu


Version 1:  (Trying to fit into the yellow color from the theme of home page)

<img width="1680" alt="version-1" src="https://user-images.githubusercontent.com/10291571/87249396-7f5cd300-c47c-11ea-8802-8dbc656f0ee2.png">
Version 2: (trying to fit into gray background of the header and footer)

Note:
 - List is supposed to be visible on click/hover
 - _2019_ and _Español_ are in _**hover**_ state
<img width="1680" alt="version-2" src="https://user-images.githubusercontent.com/10291571/87249433-aadfbd80-c47c-11ea-9684-a5c18238b1a0.png">

@rviscomi What are your thoughts on these? Also please add anyone else into the thread, would love to get some design reviews on this attempt 😁

**Comment by bazzadp** [comment]
Thanks for those mockups @sudheendrachari 

My feedback:
- Agree with removing the rounded corners for the reason you give. Also solves #892 
- Not sure I agree with replacing the chevron with icons. The lead to misunderstanding. The date icon makes me think it’s a date picker rather than a year picker and not sure what the language picker icon is? I think the chevron is simple and well understood.
- Not sure I like the yellow. To me these are secondary call to actions and think yellow should be for primary CTAs.
- Need to be very careful on click and hover. This needs to work on mobile and we’ve spent a lot of time in accessibility and keyboard support. Not sure if you’re just using those terms to mean hover, focus or active but keep that in mind.
- Need to consider keyboard support (up/down/esc and typing). There’s a lot you get with the native select, though ability to style it not one of them. This is a good article in this: https://www.smashingmagazine.com/2017/11/building-accessible-menu-systems/
- Will be interesting to see how this works on mobile.
- Should language menu be left-side aligned to stop it going off screen like it looks like it might?

These are minor tweaks and some or personal opinion. Looks good to me in general though and think it’s worth moving to developing so we can really see what it plays like.

Hope that’s helpful feedback and thanks again for working on this!

**Comment by bazzadp** [comment]
On mobile could this be a problem as years (and hopefully languages!) grow? I quite like the native select for iOS For long lists. Not an Android user so dunno what it looks like there but maybe should consider keeping native select for mobile view?

**Comment by rviscomi** [comment]
+1 thanks @sudheendrachari!

> Agree with removing the rounded corners for the reason you give. Also solves #892

Other buttons on the site use these corners, so I think it's important to keep them consistent. I made a suggestion in #892 to address the outline issue. It also applies to `.btn:focus` styles.

> Not sure I agree with replacing the chevron with icons. The lead to misunderstanding. The date icon makes me think it’s a date picker rather than a year picker and not sure what the language picker icon is? I think the chevron is simple and well understood.

+1

> Not sure I like the yellow. To me these are secondary call to actions and think yellow should be for primary CTAs.

+1


So to sum up, I think the dropdown button itself is already well-designed overall, but the challenge in this issue is to develop a menu that fits within the existing UI patterns.

**Comment by bazzadp** [comment]
How’s this going @sudheendrachari ? Anything we can help you on?
